// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/ingest-exercises.js used to seed ExerciseDB data.

export interface ExerciseOption {
    id: string;
    name: string;
    met: number;
}

export const EXERCISE_DB: ExerciseOption[] = [
    {
        "id": "3_4_Sit-Up",
        "name": "3/4 Sit-Up",
        "met": 3
    },
    {
        "id": "90_90_Hamstring",
        "name": "90/90 Hamstring",
        "met": 2
    },
    {
        "id": "Ab_Crunch_Machine",
        "name": "Ab Crunch Machine",
        "met": 8
    },
    {
        "id": "Ab_Roller",
        "name": "Ab Roller",
        "met": 3
    },
    {
        "id": "Adductor",
        "name": "Adductor",
        "met": 2
    },
    {
        "id": "Adductor_Groin",
        "name": "Adductor/Groin",
        "met": 2
    },
    {
        "id": "Advanced_Kettlebell_Windmill",
        "name": "Advanced Kettlebell Windmill",
        "met": 3
    },
    {
        "id": "Air_Bike",
        "name": "Air Bike",
        "met": 7
    },
    {
        "id": "All_Fours_Quad_Stretch",
        "name": "All Fours Quad Stretch",
        "met": 2
    },
    {
        "id": "Alternate_Hammer_Curl",
        "name": "Alternate Hammer Curl",
        "met": 3
    },
    {
        "id": "Alternate_Heel_Touchers",
        "name": "Alternate Heel Touchers",
        "met": 3
    },
    {
        "id": "Alternate_Incline_Dumbbell_Curl",
        "name": "Alternate Incline Dumbbell Curl",
        "met": 3
    },
    {
        "id": "Alternate_Leg_Diagonal_Bound",
        "name": "Alternate Leg Diagonal Bound",
        "met": 8
    },
    {
        "id": "Alternating_Cable_Shoulder_Press",
        "name": "Alternating Cable Shoulder Press",
        "met": 3
    },
    {
        "id": "Alternating_Deltoid_Raise",
        "name": "Alternating Deltoid Raise",
        "met": 3
    },
    {
        "id": "Alternating_Floor_Press",
        "name": "Alternating Floor Press",
        "met": 3
    },
    {
        "id": "Alternating_Hang_Clean",
        "name": "Alternating Hang Clean",
        "met": 3
    },
    {
        "id": "Alternating_Kettlebell_Press",
        "name": "Alternating Kettlebell Press",
        "met": 3
    },
    {
        "id": "Alternating_Kettlebell_Row",
        "name": "Alternating Kettlebell Row",
        "met": 3
    },
    {
        "id": "Alternating_Renegade_Row",
        "name": "Alternating Renegade Row",
        "met": 3
    },
    {
        "id": "Ankle_Circles",
        "name": "Ankle Circles",
        "met": 2
    },
    {
        "id": "Ankle_On_The_Knee",
        "name": "Ankle On The Knee",
        "met": 2
    },
    {
        "id": "Anterior_Tibialis-SMR",
        "name": "Anterior Tibialis-SMR",
        "met": 2
    },
    {
        "id": "Anti-Gravity_Press",
        "name": "Anti-Gravity Press",
        "met": 3
    },
    {
        "id": "Arm_Circles",
        "name": "Arm Circles",
        "met": 2
    },
    {
        "id": "Arnold_Dumbbell_Press",
        "name": "Arnold Dumbbell Press",
        "met": 3
    },
    {
        "id": "Around_The_Worlds",
        "name": "Around The Worlds",
        "met": 3
    },
    {
        "id": "Atlas_Stone_Trainer",
        "name": "Atlas Stone Trainer",
        "met": 6
    },
    {
        "id": "Atlas_Stones",
        "name": "Atlas Stones",
        "met": 6
    },
    {
        "id": "Axle_Deadlift",
        "name": "Axle Deadlift",
        "met": 6
    },
    {
        "id": "Back_Flyes_-_With_Bands",
        "name": "Back Flyes - With Bands",
        "met": 3
    },
    {
        "id": "Backward_Drag",
        "name": "Backward Drag",
        "met": 6
    },
    {
        "id": "Backward_Medicine_Ball_Throw",
        "name": "Backward Medicine Ball Throw",
        "met": 8
    },
    {
        "id": "Balance_Board",
        "name": "Balance Board",
        "met": 3
    },
    {
        "id": "Ball_Leg_Curl",
        "name": "Ball Leg Curl",
        "met": 3
    },
    {
        "id": "Band_Assisted_Pull-Up",
        "name": "Band Assisted Pull-Up",
        "met": 3
    },
    {
        "id": "Band_Good_Morning",
        "name": "Band Good Morning",
        "met": 6
    },
    {
        "id": "Band_Good_Morning_Pull_Through",
        "name": "Band Good Morning (Pull Through)",
        "met": 6
    },
    {
        "id": "Band_Hip_Adductions",
        "name": "Band Hip Adductions",
        "met": 3
    },
    {
        "id": "Band_Pull_Apart",
        "name": "Band Pull Apart",
        "met": 3
    },
    {
        "id": "Band_Skull_Crusher",
        "name": "Band Skull Crusher",
        "met": 3
    },
    {
        "id": "Barbell_Ab_Rollout",
        "name": "Barbell Ab Rollout",
        "met": 3
    },
    {
        "id": "Barbell_Ab_Rollout_-_On_Knees",
        "name": "Barbell Ab Rollout - On Knees",
        "met": 3
    },
    {
        "id": "Barbell_Bench_Press_-_Medium_Grip",
        "name": "Barbell Bench Press - Medium Grip",
        "met": 3
    },
    {
        "id": "Barbell_Curl",
        "name": "Barbell Curl",
        "met": 3
    },
    {
        "id": "Barbell_Curls_Lying_Against_An_Incline",
        "name": "Barbell Curls Lying Against An Incline",
        "met": 3
    },
    {
        "id": "Barbell_Deadlift",
        "name": "Barbell Deadlift",
        "met": 3
    },
    {
        "id": "Barbell_Full_Squat",
        "name": "Barbell Full Squat",
        "met": 3
    },
    {
        "id": "Barbell_Glute_Bridge",
        "name": "Barbell Glute Bridge",
        "met": 6
    },
    {
        "id": "Barbell_Guillotine_Bench_Press",
        "name": "Barbell Guillotine Bench Press",
        "met": 3
    },
    {
        "id": "Barbell_Hack_Squat",
        "name": "Barbell Hack Squat",
        "met": 3
    },
    {
        "id": "Barbell_Hip_Thrust",
        "name": "Barbell Hip Thrust",
        "met": 6
    },
    {
        "id": "Barbell_Incline_Bench_Press_-_Medium_Grip",
        "name": "Barbell Incline Bench Press - Medium Grip",
        "met": 3
    },
    {
        "id": "Barbell_Incline_Shoulder_Raise",
        "name": "Barbell Incline Shoulder Raise",
        "met": 3
    },
    {
        "id": "Barbell_Lunge",
        "name": "Barbell Lunge",
        "met": 3
    },
    {
        "id": "Barbell_Rear_Delt_Row",
        "name": "Barbell Rear Delt Row",
        "met": 3
    },
    {
        "id": "Barbell_Rollout_from_Bench",
        "name": "Barbell Rollout from Bench",
        "met": 3
    },
    {
        "id": "Barbell_Seated_Calf_Raise",
        "name": "Barbell Seated Calf Raise",
        "met": 3
    },
    {
        "id": "Barbell_Shoulder_Press",
        "name": "Barbell Shoulder Press",
        "met": 3
    },
    {
        "id": "Barbell_Shrug",
        "name": "Barbell Shrug",
        "met": 3
    },
    {
        "id": "Barbell_Shrug_Behind_The_Back",
        "name": "Barbell Shrug Behind The Back",
        "met": 3
    },
    {
        "id": "Barbell_Side_Bend",
        "name": "Barbell Side Bend",
        "met": 3
    },
    {
        "id": "Barbell_Side_Split_Squat",
        "name": "Barbell Side Split Squat",
        "met": 3
    },
    {
        "id": "Barbell_Squat",
        "name": "Barbell Squat",
        "met": 3
    },
    {
        "id": "Barbell_Squat_To_A_Bench",
        "name": "Barbell Squat To A Bench",
        "met": 3
    },
    {
        "id": "Barbell_Step_Ups",
        "name": "Barbell Step Ups",
        "met": 3
    },
    {
        "id": "Barbell_Walking_Lunge",
        "name": "Barbell Walking Lunge",
        "met": 3.5
    },
    {
        "id": "Battling_Ropes",
        "name": "Battling Ropes",
        "met": 3
    },
    {
        "id": "Bear_Crawl_Sled_Drags",
        "name": "Bear Crawl Sled Drags",
        "met": 6
    },
    {
        "id": "Behind_Head_Chest_Stretch",
        "name": "Behind Head Chest Stretch",
        "met": 2
    },
    {
        "id": "Bench_Dips",
        "name": "Bench Dips",
        "met": 3
    },
    {
        "id": "Bench_Jump",
        "name": "Bench Jump",
        "met": 8
    },
    {
        "id": "Bench_Press_-_Powerlifting",
        "name": "Bench Press - Powerlifting",
        "met": 6
    },
    {
        "id": "Bench_Press_-_With_Bands",
        "name": "Bench Press - With Bands",
        "met": 3
    },
    {
        "id": "Bench_Press_with_Chains",
        "name": "Bench Press with Chains",
        "met": 6
    },
    {
        "id": "Bench_Sprint",
        "name": "Bench Sprint",
        "met": 8
    },
    {
        "id": "Bent-Arm_Barbell_Pullover",
        "name": "Bent-Arm Barbell Pullover",
        "met": 3
    },
    {
        "id": "Bent-Arm_Dumbbell_Pullover",
        "name": "Bent-Arm Dumbbell Pullover",
        "met": 3
    },
    {
        "id": "Bent-Knee_Hip_Raise",
        "name": "Bent-Knee Hip Raise",
        "met": 3
    },
    {
        "id": "Bent_Over_Barbell_Row",
        "name": "Bent Over Barbell Row",
        "met": 3
    },
    {
        "id": "Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench",
        "name": "Bent Over Dumbbell Rear Delt Raise With Head On Bench",
        "met": 3
    },
    {
        "id": "Bent_Over_Low-Pulley_Side_Lateral",
        "name": "Bent Over Low-Pulley Side Lateral",
        "met": 3
    },
    {
        "id": "Bent_Over_One-Arm_Long_Bar_Row",
        "name": "Bent Over One-Arm Long Bar Row",
        "met": 3
    },
    {
        "id": "Bent_Over_Two-Arm_Long_Bar_Row",
        "name": "Bent Over Two-Arm Long Bar Row",
        "met": 3
    },
    {
        "id": "Bent_Over_Two-Dumbbell_Row",
        "name": "Bent Over Two-Dumbbell Row",
        "met": 3
    },
    {
        "id": "Bent_Over_Two-Dumbbell_Row_With_Palms_In",
        "name": "Bent Over Two-Dumbbell Row With Palms In",
        "met": 3
    },
    {
        "id": "Bent_Press",
        "name": "Bent Press",
        "met": 3
    },
    {
        "id": "Bicycling",
        "name": "Bicycling",
        "met": 7
    },
    {
        "id": "Bicycling_Stationary",
        "name": "Bicycling, Stationary",
        "met": 7
    },
    {
        "id": "Board_Press",
        "name": "Board Press",
        "met": 6
    },
    {
        "id": "Body-Up",
        "name": "Body-Up",
        "met": 3
    },
    {
        "id": "Body_Tricep_Press",
        "name": "Body Tricep Press",
        "met": 3
    },
    {
        "id": "Bodyweight_Flyes",
        "name": "Bodyweight Flyes",
        "met": 3
    },
    {
        "id": "Bodyweight_Mid_Row",
        "name": "Bodyweight Mid Row",
        "met": 3
    },
    {
        "id": "Bodyweight_Squat",
        "name": "Bodyweight Squat",
        "met": 3
    },
    {
        "id": "Bodyweight_Walking_Lunge",
        "name": "Bodyweight Walking Lunge",
        "met": 3.5
    },
    {
        "id": "Bosu_Ball_Cable_Crunch_With_Side_Bends",
        "name": "Bosu Ball Cable Crunch With Side Bends",
        "met": 8
    },
    {
        "id": "Bottoms-Up_Clean_From_The_Hang_Position",
        "name": "Bottoms-Up Clean From The Hang Position",
        "met": 3
    },
    {
        "id": "Bottoms_Up",
        "name": "Bottoms Up",
        "met": 3
    },
    {
        "id": "Box_Jump_Multiple_Response",
        "name": "Box Jump (Multiple Response)",
        "met": 8
    },
    {
        "id": "Box_Skip",
        "name": "Box Skip",
        "met": 8
    },
    {
        "id": "Box_Squat",
        "name": "Box Squat",
        "met": 6
    },
    {
        "id": "Box_Squat_with_Bands",
        "name": "Box Squat with Bands",
        "met": 6
    },
    {
        "id": "Box_Squat_with_Chains",
        "name": "Box Squat with Chains",
        "met": 3
    },
    {
        "id": "Brachialis-SMR",
        "name": "Brachialis-SMR",
        "met": 2
    },
    {
        "id": "Bradford_Rocky_Presses",
        "name": "Bradford/Rocky Presses",
        "met": 3
    },
    {
        "id": "Butt-Ups",
        "name": "Butt-Ups",
        "met": 3
    },
    {
        "id": "Butt_Lift_Bridge",
        "name": "Butt Lift (Bridge)",
        "met": 3
    },
    {
        "id": "Butterfly",
        "name": "Butterfly",
        "met": 3
    },
    {
        "id": "Cable_Chest_Press",
        "name": "Cable Chest Press",
        "met": 3
    },
    {
        "id": "Cable_Crossover",
        "name": "Cable Crossover",
        "met": 3
    },
    {
        "id": "Cable_Crunch",
        "name": "Cable Crunch",
        "met": 8
    },
    {
        "id": "Cable_Deadlifts",
        "name": "Cable Deadlifts",
        "met": 3
    },
    {
        "id": "Cable_Hammer_Curls_-_Rope_Attachment",
        "name": "Cable Hammer Curls - Rope Attachment",
        "met": 3
    },
    {
        "id": "Cable_Hip_Adduction",
        "name": "Cable Hip Adduction",
        "met": 3
    },
    {
        "id": "Cable_Incline_Pushdown",
        "name": "Cable Incline Pushdown",
        "met": 3
    },
    {
        "id": "Cable_Incline_Triceps_Extension",
        "name": "Cable Incline Triceps Extension",
        "met": 3
    },
    {
        "id": "Cable_Internal_Rotation",
        "name": "Cable Internal Rotation",
        "met": 3
    },
    {
        "id": "Cable_Iron_Cross",
        "name": "Cable Iron Cross",
        "met": 3
    },
    {
        "id": "Cable_Judo_Flip",
        "name": "Cable Judo Flip",
        "met": 3
    },
    {
        "id": "Cable_Lying_Triceps_Extension",
        "name": "Cable Lying Triceps Extension",
        "met": 3
    },
    {
        "id": "Cable_One_Arm_Tricep_Extension",
        "name": "Cable One Arm Tricep Extension",
        "met": 3
    },
    {
        "id": "Cable_Preacher_Curl",
        "name": "Cable Preacher Curl",
        "met": 3
    },
    {
        "id": "Cable_Rear_Delt_Fly",
        "name": "Cable Rear Delt Fly",
        "met": 3
    },
    {
        "id": "Cable_Reverse_Crunch",
        "name": "Cable Reverse Crunch",
        "met": 8
    },
    {
        "id": "Cable_Rope_Overhead_Triceps_Extension",
        "name": "Cable Rope Overhead Triceps Extension",
        "met": 3
    },
    {
        "id": "Cable_Rope_Rear-Delt_Rows",
        "name": "Cable Rope Rear-Delt Rows",
        "met": 3
    },
    {
        "id": "Cable_Russian_Twists",
        "name": "Cable Russian Twists",
        "met": 3
    },
    {
        "id": "Cable_Seated_Crunch",
        "name": "Cable Seated Crunch",
        "met": 8
    },
    {
        "id": "Cable_Seated_Lateral_Raise",
        "name": "Cable Seated Lateral Raise",
        "met": 3
    },
    {
        "id": "Cable_Shoulder_Press",
        "name": "Cable Shoulder Press",
        "met": 3
    },
    {
        "id": "Cable_Shrugs",
        "name": "Cable Shrugs",
        "met": 3
    },
    {
        "id": "Cable_Wrist_Curl",
        "name": "Cable Wrist Curl",
        "met": 3
    },
    {
        "id": "Calf-Machine_Shoulder_Shrug",
        "name": "Calf-Machine Shoulder Shrug",
        "met": 3
    },
    {
        "id": "Calf_Press",
        "name": "Calf Press",
        "met": 3
    },
    {
        "id": "Calf_Press_On_The_Leg_Press_Machine",
        "name": "Calf Press On The Leg Press Machine",
        "met": 3
    },
    {
        "id": "Calf_Raise_On_A_Dumbbell",
        "name": "Calf Raise On A Dumbbell",
        "met": 3
    },
    {
        "id": "Calf_Raises_-_With_Bands",
        "name": "Calf Raises - With Bands",
        "met": 3
    },
    {
        "id": "Calf_Stretch_Elbows_Against_Wall",
        "name": "Calf Stretch Elbows Against Wall",
        "met": 2
    },
    {
        "id": "Calf_Stretch_Hands_Against_Wall",
        "name": "Calf Stretch Hands Against Wall",
        "met": 2
    },
    {
        "id": "Calves-SMR",
        "name": "Calves-SMR",
        "met": 2
    },
    {
        "id": "Car_Deadlift",
        "name": "Car Deadlift",
        "met": 6
    },
    {
        "id": "Car_Drivers",
        "name": "Car Drivers",
        "met": 3
    },
    {
        "id": "Carioca_Quick_Step",
        "name": "Carioca Quick Step",
        "met": 8
    },
    {
        "id": "Cat_Stretch",
        "name": "Cat Stretch",
        "met": 2
    },
    {
        "id": "Catch_and_Overhead_Throw",
        "name": "Catch and Overhead Throw",
        "met": 8
    },
    {
        "id": "Chain_Handle_Extension",
        "name": "Chain Handle Extension",
        "met": 6
    },
    {
        "id": "Chain_Press",
        "name": "Chain Press",
        "met": 6
    },
    {
        "id": "Chair_Leg_Extended_Stretch",
        "name": "Chair Leg Extended Stretch",
        "met": 2
    },
    {
        "id": "Chair_Lower_Back_Stretch",
        "name": "Chair Lower Back Stretch",
        "met": 2
    },
    {
        "id": "Chair_Squat",
        "name": "Chair Squat",
        "met": 3
    },
    {
        "id": "Chair_Upper_Body_Stretch",
        "name": "Chair Upper Body Stretch",
        "met": 2
    },
    {
        "id": "Chest_And_Front_Of_Shoulder_Stretch",
        "name": "Chest And Front Of Shoulder Stretch",
        "met": 2
    },
    {
        "id": "Chest_Push_from_3_point_stance",
        "name": "Chest Push from 3 point stance",
        "met": 8
    },
    {
        "id": "Chest_Push_multiple_response",
        "name": "Chest Push (multiple response)",
        "met": 8
    },
    {
        "id": "Chest_Push_single_response",
        "name": "Chest Push (single response)",
        "met": 8
    },
    {
        "id": "Chest_Push_with_Run_Release",
        "name": "Chest Push with Run Release",
        "met": 8
    },
    {
        "id": "Chest_Stretch_on_Stability_Ball",
        "name": "Chest Stretch on Stability Ball",
        "met": 2
    },
    {
        "id": "Childs_Pose",
        "name": "Child's Pose",
        "met": 2
    },
    {
        "id": "Chin-Up",
        "name": "Chin-Up",
        "met": 3
    },
    {
        "id": "Chin_To_Chest_Stretch",
        "name": "Chin To Chest Stretch",
        "met": 2
    },
    {
        "id": "Circus_Bell",
        "name": "Circus Bell",
        "met": 6
    },
    {
        "id": "Clean",
        "name": "Clean",
        "met": 6
    },
    {
        "id": "Clean_Deadlift",
        "name": "Clean Deadlift",
        "met": 6
    },
    {
        "id": "Clean_Pull",
        "name": "Clean Pull",
        "met": 6
    },
    {
        "id": "Clean_Shrug",
        "name": "Clean Shrug",
        "met": 6
    },
    {
        "id": "Clean_and_Jerk",
        "name": "Clean and Jerk",
        "met": 6
    },
    {
        "id": "Clean_and_Press",
        "name": "Clean and Press",
        "met": 3
    },
    {
        "id": "Clean_from_Blocks",
        "name": "Clean from Blocks",
        "met": 6
    },
    {
        "id": "Clock_Push-Up",
        "name": "Clock Push-Up",
        "met": 3
    },
    {
        "id": "Close-Grip_Barbell_Bench_Press",
        "name": "Close-Grip Barbell Bench Press",
        "met": 3
    },
    {
        "id": "Close-Grip_Dumbbell_Press",
        "name": "Close-Grip Dumbbell Press",
        "met": 3
    },
    {
        "id": "Close-Grip_EZ-Bar_Curl_with_Band",
        "name": "Close-Grip EZ-Bar Curl with Band",
        "met": 3
    },
    {
        "id": "Close-Grip_EZ-Bar_Press",
        "name": "Close-Grip EZ-Bar Press",
        "met": 3
    },
    {
        "id": "Close-Grip_EZ_Bar_Curl",
        "name": "Close-Grip EZ Bar Curl",
        "met": 3
    },
    {
        "id": "Close-Grip_Front_Lat_Pulldown",
        "name": "Close-Grip Front Lat Pulldown",
        "met": 3
    },
    {
        "id": "Close-Grip_Push-Up_off_of_a_Dumbbell",
        "name": "Close-Grip Push-Up off of a Dumbbell",
        "met": 3
    },
    {
        "id": "Close-Grip_Standing_Barbell_Curl",
        "name": "Close-Grip Standing Barbell Curl",
        "met": 3
    },
    {
        "id": "Cocoons",
        "name": "Cocoons",
        "met": 3
    },
    {
        "id": "Conans_Wheel",
        "name": "Conan's Wheel",
        "met": 6
    },
    {
        "id": "Concentration_Curls",
        "name": "Concentration Curls",
        "met": 3
    },
    {
        "id": "Cross-Body_Crunch",
        "name": "Cross-Body Crunch",
        "met": 8
    },
    {
        "id": "Cross_Body_Hammer_Curl",
        "name": "Cross Body Hammer Curl",
        "met": 3
    },
    {
        "id": "Cross_Over_-_With_Bands",
        "name": "Cross Over - With Bands",
        "met": 3
    },
    {
        "id": "Crossover_Reverse_Lunge",
        "name": "Crossover Reverse Lunge",
        "met": 2
    },
    {
        "id": "Crucifix",
        "name": "Crucifix",
        "met": 6
    },
    {
        "id": "Crunch_-_Hands_Overhead",
        "name": "Crunch - Hands Overhead",
        "met": 8
    },
    {
        "id": "Crunch_-_Legs_On_Exercise_Ball",
        "name": "Crunch - Legs On Exercise Ball",
        "met": 8
    },
    {
        "id": "Crunches",
        "name": "Crunches",
        "met": 8
    },
    {
        "id": "Cuban_Press",
        "name": "Cuban Press",
        "met": 3
    },
    {
        "id": "Dancers_Stretch",
        "name": "Dancer's Stretch",
        "met": 2
    },
    {
        "id": "Dead_Bug",
        "name": "Dead Bug",
        "met": 3
    },
    {
        "id": "Deadlift_with_Bands",
        "name": "Deadlift with Bands",
        "met": 6
    },
    {
        "id": "Deadlift_with_Chains",
        "name": "Deadlift with Chains",
        "met": 6
    },
    {
        "id": "Decline_Barbell_Bench_Press",
        "name": "Decline Barbell Bench Press",
        "met": 3
    },
    {
        "id": "Decline_Close-Grip_Bench_To_Skull_Crusher",
        "name": "Decline Close-Grip Bench To Skull Crusher",
        "met": 3
    },
    {
        "id": "Decline_Crunch",
        "name": "Decline Crunch",
        "met": 8
    },
    {
        "id": "Decline_Dumbbell_Bench_Press",
        "name": "Decline Dumbbell Bench Press",
        "met": 3
    },
    {
        "id": "Decline_Dumbbell_Flyes",
        "name": "Decline Dumbbell Flyes",
        "met": 3
    },
    {
        "id": "Decline_Dumbbell_Triceps_Extension",
        "name": "Decline Dumbbell Triceps Extension",
        "met": 3
    },
    {
        "id": "Decline_EZ_Bar_Triceps_Extension",
        "name": "Decline EZ Bar Triceps Extension",
        "met": 3
    },
    {
        "id": "Decline_Oblique_Crunch",
        "name": "Decline Oblique Crunch",
        "met": 8
    },
    {
        "id": "Decline_Push-Up",
        "name": "Decline Push-Up",
        "met": 3
    },
    {
        "id": "Decline_Reverse_Crunch",
        "name": "Decline Reverse Crunch",
        "met": 8
    },
    {
        "id": "Decline_Smith_Press",
        "name": "Decline Smith Press",
        "met": 3
    },
    {
        "id": "Deficit_Deadlift",
        "name": "Deficit Deadlift",
        "met": 6
    },
    {
        "id": "Depth_Jump_Leap",
        "name": "Depth Jump Leap",
        "met": 8
    },
    {
        "id": "Dip_Machine",
        "name": "Dip Machine",
        "met": 3
    },
    {
        "id": "Dips_-_Chest_Version",
        "name": "Dips - Chest Version",
        "met": 3
    },
    {
        "id": "Dips_-_Triceps_Version",
        "name": "Dips - Triceps Version",
        "met": 3
    },
    {
        "id": "Donkey_Calf_Raises",
        "name": "Donkey Calf Raises",
        "met": 3
    },
    {
        "id": "Double_Kettlebell_Alternating_Hang_Clean",
        "name": "Double Kettlebell Alternating Hang Clean",
        "met": 3
    },
    {
        "id": "Double_Kettlebell_Jerk",
        "name": "Double Kettlebell Jerk",
        "met": 3
    },
    {
        "id": "Double_Kettlebell_Push_Press",
        "name": "Double Kettlebell Push Press",
        "met": 3
    },
    {
        "id": "Double_Kettlebell_Snatch",
        "name": "Double Kettlebell Snatch",
        "met": 3
    },
    {
        "id": "Double_Kettlebell_Windmill",
        "name": "Double Kettlebell Windmill",
        "met": 3
    },
    {
        "id": "Double_Leg_Butt_Kick",
        "name": "Double Leg Butt Kick",
        "met": 8
    },
    {
        "id": "Downward_Facing_Balance",
        "name": "Downward Facing Balance",
        "met": 3
    },
    {
        "id": "Drag_Curl",
        "name": "Drag Curl",
        "met": 3
    },
    {
        "id": "Drop_Push",
        "name": "Drop Push",
        "met": 8
    },
    {
        "id": "Dumbbell_Alternate_Bicep_Curl",
        "name": "Dumbbell Alternate Bicep Curl",
        "met": 3
    },
    {
        "id": "Dumbbell_Bench_Press",
        "name": "Dumbbell Bench Press",
        "met": 3
    },
    {
        "id": "Dumbbell_Bench_Press_with_Neutral_Grip",
        "name": "Dumbbell Bench Press with Neutral Grip",
        "met": 3
    },
    {
        "id": "Dumbbell_Bicep_Curl",
        "name": "Dumbbell Bicep Curl",
        "met": 3
    },
    {
        "id": "Dumbbell_Clean",
        "name": "Dumbbell Clean",
        "met": 3
    },
    {
        "id": "Dumbbell_Floor_Press",
        "name": "Dumbbell Floor Press",
        "met": 6
    },
    {
        "id": "Dumbbell_Flyes",
        "name": "Dumbbell Flyes",
        "met": 3
    },
    {
        "id": "Dumbbell_Incline_Row",
        "name": "Dumbbell Incline Row",
        "met": 3
    },
    {
        "id": "Dumbbell_Incline_Shoulder_Raise",
        "name": "Dumbbell Incline Shoulder Raise",
        "met": 3
    },
    {
        "id": "Dumbbell_Lunges",
        "name": "Dumbbell Lunges",
        "met": 3
    },
    {
        "id": "Dumbbell_Lying_One-Arm_Rear_Lateral_Raise",
        "name": "Dumbbell Lying One-Arm Rear Lateral Raise",
        "met": 3
    },
    {
        "id": "Dumbbell_Lying_Pronation",
        "name": "Dumbbell Lying Pronation",
        "met": 3
    },
    {
        "id": "Dumbbell_Lying_Rear_Lateral_Raise",
        "name": "Dumbbell Lying Rear Lateral Raise",
        "met": 3
    },
    {
        "id": "Dumbbell_Lying_Supination",
        "name": "Dumbbell Lying Supination",
        "met": 3
    },
    {
        "id": "Dumbbell_One-Arm_Shoulder_Press",
        "name": "Dumbbell One-Arm Shoulder Press",
        "met": 3
    },
    {
        "id": "Dumbbell_One-Arm_Triceps_Extension",
        "name": "Dumbbell One-Arm Triceps Extension",
        "met": 3
    },
    {
        "id": "Dumbbell_One-Arm_Upright_Row",
        "name": "Dumbbell One-Arm Upright Row",
        "met": 3
    },
    {
        "id": "Dumbbell_Prone_Incline_Curl",
        "name": "Dumbbell Prone Incline Curl",
        "met": 3
    },
    {
        "id": "Dumbbell_Raise",
        "name": "Dumbbell Raise",
        "met": 3
    },
    {
        "id": "Dumbbell_Rear_Lunge",
        "name": "Dumbbell Rear Lunge",
        "met": 3
    },
    {
        "id": "Dumbbell_Scaption",
        "name": "Dumbbell Scaption",
        "met": 3
    },
    {
        "id": "Dumbbell_Seated_Box_Jump",
        "name": "Dumbbell Seated Box Jump",
        "met": 8
    },
    {
        "id": "Dumbbell_Seated_One-Leg_Calf_Raise",
        "name": "Dumbbell Seated One-Leg Calf Raise",
        "met": 3
    },
    {
        "id": "Dumbbell_Shoulder_Press",
        "name": "Dumbbell Shoulder Press",
        "met": 3
    },
    {
        "id": "Dumbbell_Shrug",
        "name": "Dumbbell Shrug",
        "met": 3
    },
    {
        "id": "Dumbbell_Side_Bend",
        "name": "Dumbbell Side Bend",
        "met": 3
    },
    {
        "id": "Dumbbell_Squat",
        "name": "Dumbbell Squat",
        "met": 3
    },
    {
        "id": "Dumbbell_Squat_To_A_Bench",
        "name": "Dumbbell Squat To A Bench",
        "met": 3
    },
    {
        "id": "Dumbbell_Step_Ups",
        "name": "Dumbbell Step Ups",
        "met": 3
    },
    {
        "id": "Dumbbell_Tricep_Extension_-Pronated_Grip",
        "name": "Dumbbell Tricep Extension -Pronated Grip",
        "met": 3
    },
    {
        "id": "Dynamic_Back_Stretch",
        "name": "Dynamic Back Stretch",
        "met": 2
    },
    {
        "id": "Dynamic_Chest_Stretch",
        "name": "Dynamic Chest Stretch",
        "met": 2
    },
    {
        "id": "EZ-Bar_Curl",
        "name": "EZ-Bar Curl",
        "met": 3
    },
    {
        "id": "EZ-Bar_Skullcrusher",
        "name": "EZ-Bar Skullcrusher",
        "met": 3
    },
    {
        "id": "Elbow_Circles",
        "name": "Elbow Circles",
        "met": 2
    },
    {
        "id": "Elbow_to_Knee",
        "name": "Elbow to Knee",
        "met": 3
    },
    {
        "id": "Elbows_Back",
        "name": "Elbows Back",
        "met": 2
    },
    {
        "id": "Elevated_Back_Lunge",
        "name": "Elevated Back Lunge",
        "met": 3
    },
    {
        "id": "Elevated_Cable_Rows",
        "name": "Elevated Cable Rows",
        "met": 3
    },
    {
        "id": "Elliptical_Trainer",
        "name": "Elliptical Trainer",
        "met": 8
    },
    {
        "id": "Exercise_Ball_Crunch",
        "name": "Exercise Ball Crunch",
        "met": 8
    },
    {
        "id": "Exercise_Ball_Pull-In",
        "name": "Exercise Ball Pull-In",
        "met": 3
    },
    {
        "id": "Extended_Range_One-Arm_Kettlebell_Floor_Press",
        "name": "Extended Range One-Arm Kettlebell Floor Press",
        "met": 3
    },
    {
        "id": "External_Rotation",
        "name": "External Rotation",
        "met": 3
    },
    {
        "id": "External_Rotation_with_Band",
        "name": "External Rotation with Band",
        "met": 3
    },
    {
        "id": "External_Rotation_with_Cable",
        "name": "External Rotation with Cable",
        "met": 3
    },
    {
        "id": "Face_Pull",
        "name": "Face Pull",
        "met": 3
    },
    {
        "id": "Farmers_Walk",
        "name": "Farmer's Walk",
        "met": 3.5
    },
    {
        "id": "Fast_Skipping",
        "name": "Fast Skipping",
        "met": 8
    },
    {
        "id": "Finger_Curls",
        "name": "Finger Curls",
        "met": 3
    },
    {
        "id": "Flat_Bench_Cable_Flyes",
        "name": "Flat Bench Cable Flyes",
        "met": 3
    },
    {
        "id": "Flat_Bench_Leg_Pull-In",
        "name": "Flat Bench Leg Pull-In",
        "met": 3
    },
    {
        "id": "Flat_Bench_Lying_Leg_Raise",
        "name": "Flat Bench Lying Leg Raise",
        "met": 3
    },
    {
        "id": "Flexor_Incline_Dumbbell_Curls",
        "name": "Flexor Incline Dumbbell Curls",
        "met": 3
    },
    {
        "id": "Floor_Glute-Ham_Raise",
        "name": "Floor Glute-Ham Raise",
        "met": 3
    },
    {
        "id": "Floor_Press",
        "name": "Floor Press",
        "met": 6
    },
    {
        "id": "Floor_Press_with_Chains",
        "name": "Floor Press with Chains",
        "met": 6
    },
    {
        "id": "Flutter_Kicks",
        "name": "Flutter Kicks",
        "met": 3
    },
    {
        "id": "Foot-SMR",
        "name": "Foot-SMR",
        "met": 2
    },
    {
        "id": "Forward_Drag_with_Press",
        "name": "Forward Drag with Press",
        "met": 6
    },
    {
        "id": "Frankenstein_Squat",
        "name": "Frankenstein Squat",
        "met": 6
    },
    {
        "id": "Freehand_Jump_Squat",
        "name": "Freehand Jump Squat",
        "met": 3
    },
    {
        "id": "Frog_Hops",
        "name": "Frog Hops",
        "met": 2
    },
    {
        "id": "Frog_Sit-Ups",
        "name": "Frog Sit-Ups",
        "met": 3
    },
    {
        "id": "Front_Barbell_Squat",
        "name": "Front Barbell Squat",
        "met": 3
    },
    {
        "id": "Front_Barbell_Squat_To_A_Bench",
        "name": "Front Barbell Squat To A Bench",
        "met": 3
    },
    {
        "id": "Front_Box_Jump",
        "name": "Front Box Jump",
        "met": 8
    },
    {
        "id": "Front_Cable_Raise",
        "name": "Front Cable Raise",
        "met": 3
    },
    {
        "id": "Front_Cone_Hops_or_hurdle_hops",
        "name": "Front Cone Hops (or hurdle hops)",
        "met": 8
    },
    {
        "id": "Front_Dumbbell_Raise",
        "name": "Front Dumbbell Raise",
        "met": 3
    },
    {
        "id": "Front_Incline_Dumbbell_Raise",
        "name": "Front Incline Dumbbell Raise",
        "met": 3
    },
    {
        "id": "Front_Leg_Raises",
        "name": "Front Leg Raises",
        "met": 2
    },
    {
        "id": "Front_Plate_Raise",
        "name": "Front Plate Raise",
        "met": 3
    },
    {
        "id": "Front_Raise_And_Pullover",
        "name": "Front Raise And Pullover",
        "met": 3
    },
    {
        "id": "Front_Squat_Clean_Grip",
        "name": "Front Squat (Clean Grip)",
        "met": 3
    },
    {
        "id": "Front_Squats_With_Two_Kettlebells",
        "name": "Front Squats With Two Kettlebells",
        "met": 3
    },
    {
        "id": "Front_Two-Dumbbell_Raise",
        "name": "Front Two-Dumbbell Raise",
        "met": 3
    },
    {
        "id": "Full_Range-Of-Motion_Lat_Pulldown",
        "name": "Full Range-Of-Motion Lat Pulldown",
        "met": 3
    },
    {
        "id": "Gironda_Sternum_Chins",
        "name": "Gironda Sternum Chins",
        "met": 3
    },
    {
        "id": "Glute_Ham_Raise",
        "name": "Glute Ham Raise",
        "met": 6
    },
    {
        "id": "Glute_Kickback",
        "name": "Glute Kickback",
        "met": 3
    },
    {
        "id": "Goblet_Squat",
        "name": "Goblet Squat",
        "met": 3
    },
    {
        "id": "Good_Morning",
        "name": "Good Morning",
        "met": 6
    },
    {
        "id": "Good_Morning_off_Pins",
        "name": "Good Morning off Pins",
        "met": 6
    },
    {
        "id": "Gorilla_Chin_Crunch",
        "name": "Gorilla Chin/Crunch",
        "met": 8
    },
    {
        "id": "Groin_and_Back_Stretch",
        "name": "Groin and Back Stretch",
        "met": 2
    },
    {
        "id": "Groiners",
        "name": "Groiners",
        "met": 2
    },
    {
        "id": "Hack_Squat",
        "name": "Hack Squat",
        "met": 3
    },
    {
        "id": "Hammer_Curls",
        "name": "Hammer Curls",
        "met": 3
    },
    {
        "id": "Hammer_Grip_Incline_DB_Bench_Press",
        "name": "Hammer Grip Incline DB Bench Press",
        "met": 3
    },
    {
        "id": "Hamstring-SMR",
        "name": "Hamstring-SMR",
        "met": 2
    },
    {
        "id": "Hamstring_Stretch",
        "name": "Hamstring Stretch",
        "met": 2
    },
    {
        "id": "Handstand_Push-Ups",
        "name": "Handstand Push-Ups",
        "met": 3
    },
    {
        "id": "Hang_Clean",
        "name": "Hang Clean",
        "met": 6
    },
    {
        "id": "Hang_Clean_-_Below_the_Knees",
        "name": "Hang Clean - Below the Knees",
        "met": 6
    },
    {
        "id": "Hang_Snatch",
        "name": "Hang Snatch",
        "met": 6
    },
    {
        "id": "Hang_Snatch_-_Below_Knees",
        "name": "Hang Snatch - Below Knees",
        "met": 6
    },
    {
        "id": "Hanging_Bar_Good_Morning",
        "name": "Hanging Bar Good Morning",
        "met": 6
    },
    {
        "id": "Hanging_Leg_Raise",
        "name": "Hanging Leg Raise",
        "met": 3
    },
    {
        "id": "Hanging_Pike",
        "name": "Hanging Pike",
        "met": 3
    },
    {
        "id": "Heaving_Snatch_Balance",
        "name": "Heaving Snatch Balance",
        "met": 6
    },
    {
        "id": "Heavy_Bag_Thrust",
        "name": "Heavy Bag Thrust",
        "met": 8
    },
    {
        "id": "High_Cable_Curls",
        "name": "High Cable Curls",
        "met": 3
    },
    {
        "id": "Hip_Circles_prone",
        "name": "Hip Circles (prone)",
        "met": 2
    },
    {
        "id": "Hip_Extension_with_Bands",
        "name": "Hip Extension with Bands",
        "met": 3
    },
    {
        "id": "Hip_Flexion_with_Band",
        "name": "Hip Flexion with Band",
        "met": 3
    },
    {
        "id": "Hip_Lift_with_Band",
        "name": "Hip Lift with Band",
        "met": 6
    },
    {
        "id": "Hug_A_Ball",
        "name": "Hug A Ball",
        "met": 2
    },
    {
        "id": "Hug_Knees_To_Chest",
        "name": "Hug Knees To Chest",
        "met": 2
    },
    {
        "id": "Hurdle_Hops",
        "name": "Hurdle Hops",
        "met": 8
    },
    {
        "id": "Hyperextensions_Back_Extensions",
        "name": "Hyperextensions (Back Extensions)",
        "met": 3
    },
    {
        "id": "Hyperextensions_With_No_Hyperextension_Bench",
        "name": "Hyperextensions With No Hyperextension Bench",
        "met": 3
    },
    {
        "id": "IT_Band_and_Glute_Stretch",
        "name": "IT Band and Glute Stretch",
        "met": 2
    },
    {
        "id": "Iliotibial_Tract-SMR",
        "name": "Iliotibial Tract-SMR",
        "met": 2
    },
    {
        "id": "Inchworm",
        "name": "Inchworm",
        "met": 2
    },
    {
        "id": "Incline_Barbell_Triceps_Extension",
        "name": "Incline Barbell Triceps Extension",
        "met": 3
    },
    {
        "id": "Incline_Bench_Pull",
        "name": "Incline Bench Pull",
        "met": 3
    },
    {
        "id": "Incline_Cable_Chest_Press",
        "name": "Incline Cable Chest Press",
        "met": 3
    },
    {
        "id": "Incline_Cable_Flye",
        "name": "Incline Cable Flye",
        "met": 3
    },
    {
        "id": "Incline_Dumbbell_Bench_With_Palms_Facing_In",
        "name": "Incline Dumbbell Bench With Palms Facing In",
        "met": 3
    },
    {
        "id": "Incline_Dumbbell_Curl",
        "name": "Incline Dumbbell Curl",
        "met": 3
    },
    {
        "id": "Incline_Dumbbell_Flyes",
        "name": "Incline Dumbbell Flyes",
        "met": 3
    },
    {
        "id": "Incline_Dumbbell_Flyes_-_With_A_Twist",
        "name": "Incline Dumbbell Flyes - With A Twist",
        "met": 3
    },
    {
        "id": "Incline_Dumbbell_Press",
        "name": "Incline Dumbbell Press",
        "met": 3
    },
    {
        "id": "Incline_Hammer_Curls",
        "name": "Incline Hammer Curls",
        "met": 3
    },
    {
        "id": "Incline_Inner_Biceps_Curl",
        "name": "Incline Inner Biceps Curl",
        "met": 3
    },
    {
        "id": "Incline_Push-Up",
        "name": "Incline Push-Up",
        "met": 3
    },
    {
        "id": "Incline_Push-Up_Close-Grip",
        "name": "Incline Push-Up Close-Grip",
        "met": 3
    },
    {
        "id": "Incline_Push-Up_Depth_Jump",
        "name": "Incline Push-Up Depth Jump",
        "met": 8
    },
    {
        "id": "Incline_Push-Up_Medium",
        "name": "Incline Push-Up Medium",
        "met": 3
    },
    {
        "id": "Incline_Push-Up_Reverse_Grip",
        "name": "Incline Push-Up Reverse Grip",
        "met": 3
    },
    {
        "id": "Incline_Push-Up_Wide",
        "name": "Incline Push-Up Wide",
        "met": 3
    },
    {
        "id": "Intermediate_Groin_Stretch",
        "name": "Intermediate Groin Stretch",
        "met": 2
    },
    {
        "id": "Intermediate_Hip_Flexor_and_Quad_Stretch",
        "name": "Intermediate Hip Flexor and Quad Stretch",
        "met": 2
    },
    {
        "id": "Internal_Rotation_with_Band",
        "name": "Internal Rotation with Band",
        "met": 3
    },
    {
        "id": "Inverted_Row",
        "name": "Inverted Row",
        "met": 3
    },
    {
        "id": "Inverted_Row_with_Straps",
        "name": "Inverted Row with Straps",
        "met": 3
    },
    {
        "id": "Iron_Cross",
        "name": "Iron Cross",
        "met": 3
    },
    {
        "id": "Iron_Crosses_stretch",
        "name": "Iron Crosses (stretch)",
        "met": 2
    },
    {
        "id": "Isometric_Chest_Squeezes",
        "name": "Isometric Chest Squeezes",
        "met": 8
    },
    {
        "id": "Isometric_Neck_Exercise_-_Front_And_Back",
        "name": "Isometric Neck Exercise - Front And Back",
        "met": 3
    },
    {
        "id": "Isometric_Neck_Exercise_-_Sides",
        "name": "Isometric Neck Exercise - Sides",
        "met": 3
    },
    {
        "id": "Isometric_Wipers",
        "name": "Isometric Wipers",
        "met": 3
    },
    {
        "id": "JM_Press",
        "name": "JM Press",
        "met": 3
    },
    {
        "id": "Jackknife_Sit-Up",
        "name": "Jackknife Sit-Up",
        "met": 3
    },
    {
        "id": "Janda_Sit-Up",
        "name": "Janda Sit-Up",
        "met": 3
    },
    {
        "id": "Jefferson_Squats",
        "name": "Jefferson Squats",
        "met": 3
    },
    {
        "id": "Jerk_Balance",
        "name": "Jerk Balance",
        "met": 6
    },
    {
        "id": "Jerk_Dip_Squat",
        "name": "Jerk Dip Squat",
        "met": 6
    },
    {
        "id": "Jogging_Treadmill",
        "name": "Jogging, Treadmill",
        "met": 8
    },
    {
        "id": "Keg_Load",
        "name": "Keg Load",
        "met": 6
    },
    {
        "id": "Kettlebell_Arnold_Press",
        "name": "Kettlebell Arnold Press",
        "met": 3
    },
    {
        "id": "Kettlebell_Dead_Clean",
        "name": "Kettlebell Dead Clean",
        "met": 3
    },
    {
        "id": "Kettlebell_Figure_8",
        "name": "Kettlebell Figure 8",
        "met": 3
    },
    {
        "id": "Kettlebell_Hang_Clean",
        "name": "Kettlebell Hang Clean",
        "met": 3
    },
    {
        "id": "Kettlebell_One-Legged_Deadlift",
        "name": "Kettlebell One-Legged Deadlift",
        "met": 3
    },
    {
        "id": "Kettlebell_Pass_Between_The_Legs",
        "name": "Kettlebell Pass Between The Legs",
        "met": 3
    },
    {
        "id": "Kettlebell_Pirate_Ships",
        "name": "Kettlebell Pirate Ships",
        "met": 3
    },
    {
        "id": "Kettlebell_Pistol_Squat",
        "name": "Kettlebell Pistol Squat",
        "met": 3
    },
    {
        "id": "Kettlebell_Seated_Press",
        "name": "Kettlebell Seated Press",
        "met": 3
    },
    {
        "id": "Kettlebell_Seesaw_Press",
        "name": "Kettlebell Seesaw Press",
        "met": 3
    },
    {
        "id": "Kettlebell_Sumo_High_Pull",
        "name": "Kettlebell Sumo High Pull",
        "met": 3
    },
    {
        "id": "Kettlebell_Thruster",
        "name": "Kettlebell Thruster",
        "met": 3
    },
    {
        "id": "Kettlebell_Turkish_Get-Up_Lunge_style",
        "name": "Kettlebell Turkish Get-Up (Lunge style)",
        "met": 3
    },
    {
        "id": "Kettlebell_Turkish_Get-Up_Squat_style",
        "name": "Kettlebell Turkish Get-Up (Squat style)",
        "met": 3
    },
    {
        "id": "Kettlebell_Windmill",
        "name": "Kettlebell Windmill",
        "met": 3
    },
    {
        "id": "Kipping_Muscle_Up",
        "name": "Kipping Muscle Up",
        "met": 3
    },
    {
        "id": "Knee_Across_The_Body",
        "name": "Knee Across The Body",
        "met": 2
    },
    {
        "id": "Knee_Circles",
        "name": "Knee Circles",
        "met": 2
    },
    {
        "id": "Knee_Hip_Raise_On_Parallel_Bars",
        "name": "Knee/Hip Raise On Parallel Bars",
        "met": 3
    },
    {
        "id": "Knee_Tuck_Jump",
        "name": "Knee Tuck Jump",
        "met": 8
    },
    {
        "id": "Kneeling_Arm_Drill",
        "name": "Kneeling Arm Drill",
        "met": 8
    },
    {
        "id": "Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists",
        "name": "Kneeling Cable Crunch With Alternating Oblique Twists",
        "met": 8
    },
    {
        "id": "Kneeling_Cable_Triceps_Extension",
        "name": "Kneeling Cable Triceps Extension",
        "met": 3
    },
    {
        "id": "Kneeling_Forearm_Stretch",
        "name": "Kneeling Forearm Stretch",
        "met": 2
    },
    {
        "id": "Kneeling_High_Pulley_Row",
        "name": "Kneeling High Pulley Row",
        "met": 3
    },
    {
        "id": "Kneeling_Hip_Flexor",
        "name": "Kneeling Hip Flexor",
        "met": 2
    },
    {
        "id": "Kneeling_Jump_Squat",
        "name": "Kneeling Jump Squat",
        "met": 6
    },
    {
        "id": "Kneeling_Single-Arm_High_Pulley_Row",
        "name": "Kneeling Single-Arm High Pulley Row",
        "met": 3
    },
    {
        "id": "Kneeling_Squat",
        "name": "Kneeling Squat",
        "met": 6
    },
    {
        "id": "Landmine_180s",
        "name": "Landmine 180's",
        "met": 3
    },
    {
        "id": "Landmine_Linear_Jammer",
        "name": "Landmine Linear Jammer",
        "met": 3
    },
    {
        "id": "Lateral_Bound",
        "name": "Lateral Bound",
        "met": 8
    },
    {
        "id": "Lateral_Box_Jump",
        "name": "Lateral Box Jump",
        "met": 8
    },
    {
        "id": "Lateral_Cone_Hops",
        "name": "Lateral Cone Hops",
        "met": 8
    },
    {
        "id": "Lateral_Raise_-_With_Bands",
        "name": "Lateral Raise - With Bands",
        "met": 3
    },
    {
        "id": "Latissimus_Dorsi-SMR",
        "name": "Latissimus Dorsi-SMR",
        "met": 2
    },
    {
        "id": "Leg-Over_Floor_Press",
        "name": "Leg-Over Floor Press",
        "met": 3
    },
    {
        "id": "Leg-Up_Hamstring_Stretch",
        "name": "Leg-Up Hamstring Stretch",
        "met": 2
    },
    {
        "id": "Leg_Extensions",
        "name": "Leg Extensions",
        "met": 3
    },
    {
        "id": "Leg_Lift",
        "name": "Leg Lift",
        "met": 3
    },
    {
        "id": "Leg_Press",
        "name": "Leg Press",
        "met": 3
    },
    {
        "id": "Leg_Pull-In",
        "name": "Leg Pull-In",
        "met": 3
    },
    {
        "id": "Leverage_Chest_Press",
        "name": "Leverage Chest Press",
        "met": 3
    },
    {
        "id": "Leverage_Deadlift",
        "name": "Leverage Deadlift",
        "met": 3
    },
    {
        "id": "Leverage_Decline_Chest_Press",
        "name": "Leverage Decline Chest Press",
        "met": 3
    },
    {
        "id": "Leverage_High_Row",
        "name": "Leverage High Row",
        "met": 3
    },
    {
        "id": "Leverage_Incline_Chest_Press",
        "name": "Leverage Incline Chest Press",
        "met": 3
    },
    {
        "id": "Leverage_Iso_Row",
        "name": "Leverage Iso Row",
        "met": 3
    },
    {
        "id": "Leverage_Shoulder_Press",
        "name": "Leverage Shoulder Press",
        "met": 3
    },
    {
        "id": "Leverage_Shrug",
        "name": "Leverage Shrug",
        "met": 3
    },
    {
        "id": "Linear_3-Part_Start_Technique",
        "name": "Linear 3-Part Start Technique",
        "met": 8
    },
    {
        "id": "Linear_Acceleration_Wall_Drill",
        "name": "Linear Acceleration Wall Drill",
        "met": 8
    },
    {
        "id": "Linear_Depth_Jump",
        "name": "Linear Depth Jump",
        "met": 8
    },
    {
        "id": "Log_Lift",
        "name": "Log Lift",
        "met": 6
    },
    {
        "id": "London_Bridges",
        "name": "London Bridges",
        "met": 3
    },
    {
        "id": "Looking_At_Ceiling",
        "name": "Looking At Ceiling",
        "met": 2
    },
    {
        "id": "Low_Cable_Crossover",
        "name": "Low Cable Crossover",
        "met": 3
    },
    {
        "id": "Low_Cable_Triceps_Extension",
        "name": "Low Cable Triceps Extension",
        "met": 3
    },
    {
        "id": "Low_Pulley_Row_To_Neck",
        "name": "Low Pulley Row To Neck",
        "met": 3
    },
    {
        "id": "Lower_Back-SMR",
        "name": "Lower Back-SMR",
        "met": 2
    },
    {
        "id": "Lower_Back_Curl",
        "name": "Lower Back Curl",
        "met": 2
    },
    {
        "id": "Lunge_Pass_Through",
        "name": "Lunge Pass Through",
        "met": 3
    },
    {
        "id": "Lunge_Sprint",
        "name": "Lunge Sprint",
        "met": 3
    },
    {
        "id": "Lying_Bent_Leg_Groin",
        "name": "Lying Bent Leg Groin",
        "met": 2
    },
    {
        "id": "Lying_Cable_Curl",
        "name": "Lying Cable Curl",
        "met": 3
    },
    {
        "id": "Lying_Cambered_Barbell_Row",
        "name": "Lying Cambered Barbell Row",
        "met": 3
    },
    {
        "id": "Lying_Close-Grip_Bar_Curl_On_High_Pulley",
        "name": "Lying Close-Grip Bar Curl On High Pulley",
        "met": 3
    },
    {
        "id": "Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head",
        "name": "Lying Close-Grip Barbell Triceps Extension Behind The Head",
        "met": 3
    },
    {
        "id": "Lying_Close-Grip_Barbell_Triceps_Press_To_Chin",
        "name": "Lying Close-Grip Barbell Triceps Press To Chin",
        "met": 3
    },
    {
        "id": "Lying_Crossover",
        "name": "Lying Crossover",
        "met": 2
    },
    {
        "id": "Lying_Dumbbell_Tricep_Extension",
        "name": "Lying Dumbbell Tricep Extension",
        "met": 3
    },
    {
        "id": "Lying_Face_Down_Plate_Neck_Resistance",
        "name": "Lying Face Down Plate Neck Resistance",
        "met": 3
    },
    {
        "id": "Lying_Face_Up_Plate_Neck_Resistance",
        "name": "Lying Face Up Plate Neck Resistance",
        "met": 3
    },
    {
        "id": "Lying_Glute",
        "name": "Lying Glute",
        "met": 2
    },
    {
        "id": "Lying_Hamstring",
        "name": "Lying Hamstring",
        "met": 2
    },
    {
        "id": "Lying_High_Bench_Barbell_Curl",
        "name": "Lying High Bench Barbell Curl",
        "met": 3
    },
    {
        "id": "Lying_Leg_Curls",
        "name": "Lying Leg Curls",
        "met": 3
    },
    {
        "id": "Lying_Machine_Squat",
        "name": "Lying Machine Squat",
        "met": 3
    },
    {
        "id": "Lying_One-Arm_Lateral_Raise",
        "name": "Lying One-Arm Lateral Raise",
        "met": 3
    },
    {
        "id": "Lying_Prone_Quadriceps",
        "name": "Lying Prone Quadriceps",
        "met": 2
    },
    {
        "id": "Lying_Rear_Delt_Raise",
        "name": "Lying Rear Delt Raise",
        "met": 3
    },
    {
        "id": "Lying_Supine_Dumbbell_Curl",
        "name": "Lying Supine Dumbbell Curl",
        "met": 3
    },
    {
        "id": "Lying_T-Bar_Row",
        "name": "Lying T-Bar Row",
        "met": 3
    },
    {
        "id": "Lying_Triceps_Press",
        "name": "Lying Triceps Press",
        "met": 3
    },
    {
        "id": "Machine_Bench_Press",
        "name": "Machine Bench Press",
        "met": 3
    },
    {
        "id": "Machine_Bicep_Curl",
        "name": "Machine Bicep Curl",
        "met": 3
    },
    {
        "id": "Machine_Preacher_Curls",
        "name": "Machine Preacher Curls",
        "met": 3
    },
    {
        "id": "Machine_Shoulder_Military_Press",
        "name": "Machine Shoulder (Military) Press",
        "met": 3
    },
    {
        "id": "Machine_Triceps_Extension",
        "name": "Machine Triceps Extension",
        "met": 3
    },
    {
        "id": "Medicine_Ball_Chest_Pass",
        "name": "Medicine Ball Chest Pass",
        "met": 8
    },
    {
        "id": "Medicine_Ball_Full_Twist",
        "name": "Medicine Ball Full Twist",
        "met": 8
    },
    {
        "id": "Medicine_Ball_Scoop_Throw",
        "name": "Medicine Ball Scoop Throw",
        "met": 8
    },
    {
        "id": "Middle_Back_Shrug",
        "name": "Middle Back Shrug",
        "met": 3
    },
    {
        "id": "Middle_Back_Stretch",
        "name": "Middle Back Stretch",
        "met": 2
    },
    {
        "id": "Mixed_Grip_Chin",
        "name": "Mixed Grip Chin",
        "met": 3
    },
    {
        "id": "Monster_Walk",
        "name": "Monster Walk",
        "met": 3.5
    },
    {
        "id": "Mountain_Climbers",
        "name": "Mountain Climbers",
        "met": 8
    },
    {
        "id": "Moving_Claw_Series",
        "name": "Moving Claw Series",
        "met": 8
    },
    {
        "id": "Muscle_Snatch",
        "name": "Muscle Snatch",
        "met": 6
    },
    {
        "id": "Muscle_Up",
        "name": "Muscle Up",
        "met": 3
    },
    {
        "id": "Narrow_Stance_Hack_Squats",
        "name": "Narrow Stance Hack Squats",
        "met": 3
    },
    {
        "id": "Narrow_Stance_Leg_Press",
        "name": "Narrow Stance Leg Press",
        "met": 3
    },
    {
        "id": "Narrow_Stance_Squats",
        "name": "Narrow Stance Squats",
        "met": 3
    },
    {
        "id": "Natural_Glute_Ham_Raise",
        "name": "Natural Glute Ham Raise",
        "met": 3
    },
    {
        "id": "Neck-SMR",
        "name": "Neck-SMR",
        "met": 2
    },
    {
        "id": "Neck_Press",
        "name": "Neck Press",
        "met": 3
    },
    {
        "id": "Oblique_Crunches",
        "name": "Oblique Crunches",
        "met": 8
    },
    {
        "id": "Oblique_Crunches_-_On_The_Floor",
        "name": "Oblique Crunches - On The Floor",
        "met": 8
    },
    {
        "id": "Olympic_Squat",
        "name": "Olympic Squat",
        "met": 6
    },
    {
        "id": "On-Your-Back_Quad_Stretch",
        "name": "On-Your-Back Quad Stretch",
        "met": 2
    },
    {
        "id": "On_Your_Side_Quad_Stretch",
        "name": "On Your Side Quad Stretch",
        "met": 2
    },
    {
        "id": "One-Arm_Dumbbell_Row",
        "name": "One-Arm Dumbbell Row",
        "met": 3
    },
    {
        "id": "One-Arm_Flat_Bench_Dumbbell_Flye",
        "name": "One-Arm Flat Bench Dumbbell Flye",
        "met": 3
    },
    {
        "id": "One-Arm_High-Pulley_Cable_Side_Bends",
        "name": "One-Arm High-Pulley Cable Side Bends",
        "met": 3
    },
    {
        "id": "One-Arm_Incline_Lateral_Raise",
        "name": "One-Arm Incline Lateral Raise",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Clean",
        "name": "One-Arm Kettlebell Clean",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Clean_and_Jerk",
        "name": "One-Arm Kettlebell Clean and Jerk",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Floor_Press",
        "name": "One-Arm Kettlebell Floor Press",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Jerk",
        "name": "One-Arm Kettlebell Jerk",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Military_Press_To_The_Side",
        "name": "One-Arm Kettlebell Military Press To The Side",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Para_Press",
        "name": "One-Arm Kettlebell Para Press",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Push_Press",
        "name": "One-Arm Kettlebell Push Press",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Row",
        "name": "One-Arm Kettlebell Row",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Snatch",
        "name": "One-Arm Kettlebell Snatch",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Split_Jerk",
        "name": "One-Arm Kettlebell Split Jerk",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Split_Snatch",
        "name": "One-Arm Kettlebell Split Snatch",
        "met": 3
    },
    {
        "id": "One-Arm_Kettlebell_Swings",
        "name": "One-Arm Kettlebell Swings",
        "met": 3
    },
    {
        "id": "One-Arm_Long_Bar_Row",
        "name": "One-Arm Long Bar Row",
        "met": 3
    },
    {
        "id": "One-Arm_Medicine_Ball_Slam",
        "name": "One-Arm Medicine Ball Slam",
        "met": 3
    },
    {
        "id": "One-Arm_Open_Palm_Kettlebell_Clean",
        "name": "One-Arm Open Palm Kettlebell Clean",
        "met": 3
    },
    {
        "id": "One-Arm_Overhead_Kettlebell_Squats",
        "name": "One-Arm Overhead Kettlebell Squats",
        "met": 3
    },
    {
        "id": "One-Arm_Side_Deadlift",
        "name": "One-Arm Side Deadlift",
        "met": 3
    },
    {
        "id": "One-Arm_Side_Laterals",
        "name": "One-Arm Side Laterals",
        "met": 3
    },
    {
        "id": "One-Legged_Cable_Kickback",
        "name": "One-Legged Cable Kickback",
        "met": 3
    },
    {
        "id": "One_Arm_Against_Wall",
        "name": "One Arm Against Wall",
        "met": 2
    },
    {
        "id": "One_Arm_Chin-Up",
        "name": "One Arm Chin-Up",
        "met": 3
    },
    {
        "id": "One_Arm_Dumbbell_Bench_Press",
        "name": "One Arm Dumbbell Bench Press",
        "met": 3
    },
    {
        "id": "One_Arm_Dumbbell_Preacher_Curl",
        "name": "One Arm Dumbbell Preacher Curl",
        "met": 3
    },
    {
        "id": "One_Arm_Floor_Press",
        "name": "One Arm Floor Press",
        "met": 3
    },
    {
        "id": "One_Arm_Lat_Pulldown",
        "name": "One Arm Lat Pulldown",
        "met": 3
    },
    {
        "id": "One_Arm_Pronated_Dumbbell_Triceps_Extension",
        "name": "One Arm Pronated Dumbbell Triceps Extension",
        "met": 3
    },
    {
        "id": "One_Arm_Supinated_Dumbbell_Triceps_Extension",
        "name": "One Arm Supinated Dumbbell Triceps Extension",
        "met": 3
    },
    {
        "id": "One_Half_Locust",
        "name": "One Half Locust",
        "met": 2
    },
    {
        "id": "One_Handed_Hang",
        "name": "One Handed Hang",
        "met": 2
    },
    {
        "id": "One_Knee_To_Chest",
        "name": "One Knee To Chest",
        "met": 2
    },
    {
        "id": "One_Leg_Barbell_Squat",
        "name": "One Leg Barbell Squat",
        "met": 3
    },
    {
        "id": "Open_Palm_Kettlebell_Clean",
        "name": "Open Palm Kettlebell Clean",
        "met": 3
    },
    {
        "id": "Otis-Up",
        "name": "Otis-Up",
        "met": 3
    },
    {
        "id": "Overhead_Cable_Curl",
        "name": "Overhead Cable Curl",
        "met": 3
    },
    {
        "id": "Overhead_Lat",
        "name": "Overhead Lat",
        "met": 2
    },
    {
        "id": "Overhead_Slam",
        "name": "Overhead Slam",
        "met": 8
    },
    {
        "id": "Overhead_Squat",
        "name": "Overhead Squat",
        "met": 6
    },
    {
        "id": "Overhead_Stretch",
        "name": "Overhead Stretch",
        "met": 2
    },
    {
        "id": "Overhead_Triceps",
        "name": "Overhead Triceps",
        "met": 2
    },
    {
        "id": "Pallof_Press",
        "name": "Pallof Press",
        "met": 3
    },
    {
        "id": "Pallof_Press_With_Rotation",
        "name": "Pallof Press With Rotation",
        "met": 3
    },
    {
        "id": "Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench",
        "name": "Palms-Down Dumbbell Wrist Curl Over A Bench",
        "met": 3
    },
    {
        "id": "Palms-Down_Wrist_Curl_Over_A_Bench",
        "name": "Palms-Down Wrist Curl Over A Bench",
        "met": 3
    },
    {
        "id": "Palms-Up_Barbell_Wrist_Curl_Over_A_Bench",
        "name": "Palms-Up Barbell Wrist Curl Over A Bench",
        "met": 3
    },
    {
        "id": "Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench",
        "name": "Palms-Up Dumbbell Wrist Curl Over A Bench",
        "met": 3
    },
    {
        "id": "Parallel_Bar_Dip",
        "name": "Parallel Bar Dip",
        "met": 3
    },
    {
        "id": "Pelvic_Tilt_Into_Bridge",
        "name": "Pelvic Tilt Into Bridge",
        "met": 2
    },
    {
        "id": "Peroneals-SMR",
        "name": "Peroneals-SMR",
        "met": 2
    },
    {
        "id": "Peroneals_Stretch",
        "name": "Peroneals Stretch",
        "met": 2
    },
    {
        "id": "Physioball_Hip_Bridge",
        "name": "Physioball Hip Bridge",
        "met": 3
    },
    {
        "id": "Pin_Presses",
        "name": "Pin Presses",
        "met": 6
    },
    {
        "id": "Piriformis-SMR",
        "name": "Piriformis-SMR",
        "met": 2
    },
    {
        "id": "Plank",
        "name": "Plank",
        "met": 3
    },
    {
        "id": "Plate_Pinch",
        "name": "Plate Pinch",
        "met": 3
    },
    {
        "id": "Plate_Twist",
        "name": "Plate Twist",
        "met": 3
    },
    {
        "id": "Platform_Hamstring_Slides",
        "name": "Platform Hamstring Slides",
        "met": 3
    },
    {
        "id": "Plie_Dumbbell_Squat",
        "name": "Plie Dumbbell Squat",
        "met": 3
    },
    {
        "id": "Plyo_Kettlebell_Pushups",
        "name": "Plyo Kettlebell Pushups",
        "met": 3
    },
    {
        "id": "Plyo_Push-up",
        "name": "Plyo Push-up",
        "met": 8
    },
    {
        "id": "Posterior_Tibialis_Stretch",
        "name": "Posterior Tibialis Stretch",
        "met": 2
    },
    {
        "id": "Power_Clean",
        "name": "Power Clean",
        "met": 3
    },
    {
        "id": "Power_Clean_from_Blocks",
        "name": "Power Clean from Blocks",
        "met": 6
    },
    {
        "id": "Power_Jerk",
        "name": "Power Jerk",
        "met": 6
    },
    {
        "id": "Power_Partials",
        "name": "Power Partials",
        "met": 3
    },
    {
        "id": "Power_Snatch",
        "name": "Power Snatch",
        "met": 6
    },
    {
        "id": "Power_Snatch_from_Blocks",
        "name": "Power Snatch from Blocks",
        "met": 6
    },
    {
        "id": "Power_Stairs",
        "name": "Power Stairs",
        "met": 6
    },
    {
        "id": "Preacher_Curl",
        "name": "Preacher Curl",
        "met": 3
    },
    {
        "id": "Preacher_Hammer_Dumbbell_Curl",
        "name": "Preacher Hammer Dumbbell Curl",
        "met": 3
    },
    {
        "id": "Press_Sit-Up",
        "name": "Press Sit-Up",
        "met": 3
    },
    {
        "id": "Prone_Manual_Hamstring",
        "name": "Prone Manual Hamstring",
        "met": 3
    },
    {
        "id": "Prowler_Sprint",
        "name": "Prowler Sprint",
        "met": 8
    },
    {
        "id": "Pull_Through",
        "name": "Pull Through",
        "met": 3
    },
    {
        "id": "Pullups",
        "name": "Pullups",
        "met": 3
    },
    {
        "id": "Push-Up_Wide",
        "name": "Push-Up Wide",
        "met": 3
    },
    {
        "id": "Push-Ups_-_Close_Triceps_Position",
        "name": "Push-Ups - Close Triceps Position",
        "met": 3
    },
    {
        "id": "Push-Ups_With_Feet_Elevated",
        "name": "Push-Ups With Feet Elevated",
        "met": 3
    },
    {
        "id": "Push-Ups_With_Feet_On_An_Exercise_Ball",
        "name": "Push-Ups With Feet On An Exercise Ball",
        "met": 3
    },
    {
        "id": "Push_Press",
        "name": "Push Press",
        "met": 6
    },
    {
        "id": "Push_Press_-_Behind_the_Neck",
        "name": "Push Press - Behind the Neck",
        "met": 6
    },
    {
        "id": "Push_Up_to_Side_Plank",
        "name": "Push Up to Side Plank",
        "met": 3
    },
    {
        "id": "Pushups",
        "name": "Pushups",
        "met": 3
    },
    {
        "id": "Pushups_Close_and_Wide_Hand_Positions",
        "name": "Pushups (Close and Wide Hand Positions)",
        "met": 3
    },
    {
        "id": "Pyramid",
        "name": "Pyramid",
        "met": 2
    },
    {
        "id": "Quad_Stretch",
        "name": "Quad Stretch",
        "met": 2
    },
    {
        "id": "Quadriceps-SMR",
        "name": "Quadriceps-SMR",
        "met": 2
    },
    {
        "id": "Quick_Leap",
        "name": "Quick Leap",
        "met": 8
    },
    {
        "id": "Rack_Delivery",
        "name": "Rack Delivery",
        "met": 6
    },
    {
        "id": "Rack_Pull_with_Bands",
        "name": "Rack Pull with Bands",
        "met": 6
    },
    {
        "id": "Rack_Pulls",
        "name": "Rack Pulls",
        "met": 6
    },
    {
        "id": "Rear_Leg_Raises",
        "name": "Rear Leg Raises",
        "met": 2
    },
    {
        "id": "Recumbent_Bike",
        "name": "Recumbent Bike",
        "met": 7
    },
    {
        "id": "Return_Push_from_Stance",
        "name": "Return Push from Stance",
        "met": 8
    },
    {
        "id": "Reverse_Band_Bench_Press",
        "name": "Reverse Band Bench Press",
        "met": 6
    },
    {
        "id": "Reverse_Band_Box_Squat",
        "name": "Reverse Band Box Squat",
        "met": 6
    },
    {
        "id": "Reverse_Band_Deadlift",
        "name": "Reverse Band Deadlift",
        "met": 6
    },
    {
        "id": "Reverse_Band_Power_Squat",
        "name": "Reverse Band Power Squat",
        "met": 6
    },
    {
        "id": "Reverse_Band_Sumo_Deadlift",
        "name": "Reverse Band Sumo Deadlift",
        "met": 6
    },
    {
        "id": "Reverse_Barbell_Curl",
        "name": "Reverse Barbell Curl",
        "met": 3
    },
    {
        "id": "Reverse_Barbell_Preacher_Curls",
        "name": "Reverse Barbell Preacher Curls",
        "met": 3
    },
    {
        "id": "Reverse_Cable_Curl",
        "name": "Reverse Cable Curl",
        "met": 3
    },
    {
        "id": "Reverse_Crunch",
        "name": "Reverse Crunch",
        "met": 8
    },
    {
        "id": "Reverse_Flyes",
        "name": "Reverse Flyes",
        "met": 3
    },
    {
        "id": "Reverse_Flyes_With_External_Rotation",
        "name": "Reverse Flyes With External Rotation",
        "met": 3
    },
    {
        "id": "Reverse_Grip_Bent-Over_Rows",
        "name": "Reverse Grip Bent-Over Rows",
        "met": 3
    },
    {
        "id": "Reverse_Grip_Triceps_Pushdown",
        "name": "Reverse Grip Triceps Pushdown",
        "met": 3
    },
    {
        "id": "Reverse_Hyperextension",
        "name": "Reverse Hyperextension",
        "met": 3
    },
    {
        "id": "Reverse_Machine_Flyes",
        "name": "Reverse Machine Flyes",
        "met": 3
    },
    {
        "id": "Reverse_Plate_Curls",
        "name": "Reverse Plate Curls",
        "met": 3
    },
    {
        "id": "Reverse_Triceps_Bench_Press",
        "name": "Reverse Triceps Bench Press",
        "met": 3
    },
    {
        "id": "Rhomboids-SMR",
        "name": "Rhomboids-SMR",
        "met": 2
    },
    {
        "id": "Rickshaw_Carry",
        "name": "Rickshaw Carry",
        "met": 6
    },
    {
        "id": "Rickshaw_Deadlift",
        "name": "Rickshaw Deadlift",
        "met": 6
    },
    {
        "id": "Ring_Dips",
        "name": "Ring Dips",
        "met": 3
    },
    {
        "id": "Rocket_Jump",
        "name": "Rocket Jump",
        "met": 8
    },
    {
        "id": "Rocking_Standing_Calf_Raise",
        "name": "Rocking Standing Calf Raise",
        "met": 3
    },
    {
        "id": "Rocky_Pull-Ups_Pulldowns",
        "name": "Rocky Pull-Ups/Pulldowns",
        "met": 3
    },
    {
        "id": "Romanian_Deadlift",
        "name": "Romanian Deadlift",
        "met": 3
    },
    {
        "id": "Romanian_Deadlift_from_Deficit",
        "name": "Romanian Deadlift from Deficit",
        "met": 6
    },
    {
        "id": "Rope_Climb",
        "name": "Rope Climb",
        "met": 3
    },
    {
        "id": "Rope_Crunch",
        "name": "Rope Crunch",
        "met": 8
    },
    {
        "id": "Rope_Jumping",
        "name": "Rope Jumping",
        "met": 8
    },
    {
        "id": "Rope_Straight-Arm_Pulldown",
        "name": "Rope Straight-Arm Pulldown",
        "met": 3
    },
    {
        "id": "Round_The_World_Shoulder_Stretch",
        "name": "Round The World Shoulder Stretch",
        "met": 2
    },
    {
        "id": "Rowing_Stationary",
        "name": "Rowing, Stationary",
        "met": 7
    },
    {
        "id": "Runners_Stretch",
        "name": "Runner's Stretch",
        "met": 8
    },
    {
        "id": "Running_Treadmill",
        "name": "Running, Treadmill",
        "met": 8
    },
    {
        "id": "Russian_Twist",
        "name": "Russian Twist",
        "met": 3
    },
    {
        "id": "Sandbag_Load",
        "name": "Sandbag Load",
        "met": 6
    },
    {
        "id": "Scapular_Pull-Up",
        "name": "Scapular Pull-Up",
        "met": 3
    },
    {
        "id": "Scissor_Kick",
        "name": "Scissor Kick",
        "met": 2
    },
    {
        "id": "Scissors_Jump",
        "name": "Scissors Jump",
        "met": 8
    },
    {
        "id": "Seated_Band_Hamstring_Curl",
        "name": "Seated Band Hamstring Curl",
        "met": 3
    },
    {
        "id": "Seated_Barbell_Military_Press",
        "name": "Seated Barbell Military Press",
        "met": 3
    },
    {
        "id": "Seated_Barbell_Twist",
        "name": "Seated Barbell Twist",
        "met": 3
    },
    {
        "id": "Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension",
        "name": "Seated Bent-Over One-Arm Dumbbell Triceps Extension",
        "met": 3
    },
    {
        "id": "Seated_Bent-Over_Rear_Delt_Raise",
        "name": "Seated Bent-Over Rear Delt Raise",
        "met": 3
    },
    {
        "id": "Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension",
        "name": "Seated Bent-Over Two-Arm Dumbbell Triceps Extension",
        "met": 3
    },
    {
        "id": "Seated_Biceps",
        "name": "Seated Biceps",
        "met": 2
    },
    {
        "id": "Seated_Cable_Rows",
        "name": "Seated Cable Rows",
        "met": 3
    },
    {
        "id": "Seated_Cable_Shoulder_Press",
        "name": "Seated Cable Shoulder Press",
        "met": 3
    },
    {
        "id": "Seated_Calf_Raise",
        "name": "Seated Calf Raise",
        "met": 3
    },
    {
        "id": "Seated_Calf_Stretch",
        "name": "Seated Calf Stretch",
        "met": 2
    },
    {
        "id": "Seated_Close-Grip_Concentration_Barbell_Curl",
        "name": "Seated Close-Grip Concentration Barbell Curl",
        "met": 3
    },
    {
        "id": "Seated_Dumbbell_Curl",
        "name": "Seated Dumbbell Curl",
        "met": 3
    },
    {
        "id": "Seated_Dumbbell_Inner_Biceps_Curl",
        "name": "Seated Dumbbell Inner Biceps Curl",
        "met": 3
    },
    {
        "id": "Seated_Dumbbell_Palms-Down_Wrist_Curl",
        "name": "Seated Dumbbell Palms-Down Wrist Curl",
        "met": 3
    },
    {
        "id": "Seated_Dumbbell_Palms-Up_Wrist_Curl",
        "name": "Seated Dumbbell Palms-Up Wrist Curl",
        "met": 3
    },
    {
        "id": "Seated_Dumbbell_Press",
        "name": "Seated Dumbbell Press",
        "met": 3
    },
    {
        "id": "Seated_Flat_Bench_Leg_Pull-In",
        "name": "Seated Flat Bench Leg Pull-In",
        "met": 3
    },
    {
        "id": "Seated_Floor_Hamstring_Stretch",
        "name": "Seated Floor Hamstring Stretch",
        "met": 2
    },
    {
        "id": "Seated_Front_Deltoid",
        "name": "Seated Front Deltoid",
        "met": 2
    },
    {
        "id": "Seated_Glute",
        "name": "Seated Glute",
        "met": 2
    },
    {
        "id": "Seated_Good_Mornings",
        "name": "Seated Good Mornings",
        "met": 6
    },
    {
        "id": "Seated_Hamstring",
        "name": "Seated Hamstring",
        "met": 2
    },
    {
        "id": "Seated_Hamstring_and_Calf_Stretch",
        "name": "Seated Hamstring and Calf Stretch",
        "met": 2
    },
    {
        "id": "Seated_Head_Harness_Neck_Resistance",
        "name": "Seated Head Harness Neck Resistance",
        "met": 3
    },
    {
        "id": "Seated_Leg_Curl",
        "name": "Seated Leg Curl",
        "met": 3
    },
    {
        "id": "Seated_Leg_Tucks",
        "name": "Seated Leg Tucks",
        "met": 3
    },
    {
        "id": "Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl",
        "name": "Seated One-Arm Dumbbell Palms-Down Wrist Curl",
        "met": 3
    },
    {
        "id": "Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl",
        "name": "Seated One-Arm Dumbbell Palms-Up Wrist Curl",
        "met": 3
    },
    {
        "id": "Seated_One-arm_Cable_Pulley_Rows",
        "name": "Seated One-arm Cable Pulley Rows",
        "met": 3
    },
    {
        "id": "Seated_Overhead_Stretch",
        "name": "Seated Overhead Stretch",
        "met": 2
    },
    {
        "id": "Seated_Palm-Up_Barbell_Wrist_Curl",
        "name": "Seated Palm-Up Barbell Wrist Curl",
        "met": 3
    },
    {
        "id": "Seated_Palms-Down_Barbell_Wrist_Curl",
        "name": "Seated Palms-Down Barbell Wrist Curl",
        "met": 3
    },
    {
        "id": "Seated_Side_Lateral_Raise",
        "name": "Seated Side Lateral Raise",
        "met": 3
    },
    {
        "id": "Seated_Triceps_Press",
        "name": "Seated Triceps Press",
        "met": 3
    },
    {
        "id": "Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl",
        "name": "Seated Two-Arm Palms-Up Low-Pulley Wrist Curl",
        "met": 3
    },
    {
        "id": "See-Saw_Press_Alternating_Side_Press",
        "name": "See-Saw Press (Alternating Side Press)",
        "met": 3
    },
    {
        "id": "Shotgun_Row",
        "name": "Shotgun Row",
        "met": 3
    },
    {
        "id": "Shoulder_Circles",
        "name": "Shoulder Circles",
        "met": 2
    },
    {
        "id": "Shoulder_Press_-_With_Bands",
        "name": "Shoulder Press - With Bands",
        "met": 3
    },
    {
        "id": "Shoulder_Raise",
        "name": "Shoulder Raise",
        "met": 2
    },
    {
        "id": "Shoulder_Stretch",
        "name": "Shoulder Stretch",
        "met": 2
    },
    {
        "id": "Side-Lying_Floor_Stretch",
        "name": "Side-Lying Floor Stretch",
        "met": 2
    },
    {
        "id": "Side_Bridge",
        "name": "Side Bridge",
        "met": 3
    },
    {
        "id": "Side_Hop-Sprint",
        "name": "Side Hop-Sprint",
        "met": 8
    },
    {
        "id": "Side_Jackknife",
        "name": "Side Jackknife",
        "met": 3
    },
    {
        "id": "Side_Lateral_Raise",
        "name": "Side Lateral Raise",
        "met": 3
    },
    {
        "id": "Side_Laterals_to_Front_Raise",
        "name": "Side Laterals to Front Raise",
        "met": 3
    },
    {
        "id": "Side_Leg_Raises",
        "name": "Side Leg Raises",
        "met": 2
    },
    {
        "id": "Side_Lying_Groin_Stretch",
        "name": "Side Lying Groin Stretch",
        "met": 2
    },
    {
        "id": "Side_Neck_Stretch",
        "name": "Side Neck Stretch",
        "met": 2
    },
    {
        "id": "Side_Standing_Long_Jump",
        "name": "Side Standing Long Jump",
        "met": 8
    },
    {
        "id": "Side_To_Side_Chins",
        "name": "Side To Side Chins",
        "met": 3
    },
    {
        "id": "Side_Wrist_Pull",
        "name": "Side Wrist Pull",
        "met": 2
    },
    {
        "id": "Side_to_Side_Box_Shuffle",
        "name": "Side to Side Box Shuffle",
        "met": 8
    },
    {
        "id": "Single-Arm_Cable_Crossover",
        "name": "Single-Arm Cable Crossover",
        "met": 3
    },
    {
        "id": "Single-Arm_Linear_Jammer",
        "name": "Single-Arm Linear Jammer",
        "met": 3
    },
    {
        "id": "Single-Arm_Push-Up",
        "name": "Single-Arm Push-Up",
        "met": 3
    },
    {
        "id": "Single-Cone_Sprint_Drill",
        "name": "Single-Cone Sprint Drill",
        "met": 8
    },
    {
        "id": "Single-Leg_High_Box_Squat",
        "name": "Single-Leg High Box Squat",
        "met": 3
    },
    {
        "id": "Single-Leg_Hop_Progression",
        "name": "Single-Leg Hop Progression",
        "met": 8
    },
    {
        "id": "Single-Leg_Lateral_Hop",
        "name": "Single-Leg Lateral Hop",
        "met": 8
    },
    {
        "id": "Single-Leg_Leg_Extension",
        "name": "Single-Leg Leg Extension",
        "met": 3
    },
    {
        "id": "Single-Leg_Stride_Jump",
        "name": "Single-Leg Stride Jump",
        "met": 8
    },
    {
        "id": "Single_Dumbbell_Raise",
        "name": "Single Dumbbell Raise",
        "met": 3
    },
    {
        "id": "Single_Leg_Butt_Kick",
        "name": "Single Leg Butt Kick",
        "met": 8
    },
    {
        "id": "Single_Leg_Glute_Bridge",
        "name": "Single Leg Glute Bridge",
        "met": 3
    },
    {
        "id": "Single_Leg_Push-off",
        "name": "Single Leg Push-off",
        "met": 8
    },
    {
        "id": "Sit-Up",
        "name": "Sit-Up",
        "met": 3
    },
    {
        "id": "Sit_Squats",
        "name": "Sit Squats",
        "met": 2
    },
    {
        "id": "Skating",
        "name": "Skating",
        "met": 8
    },
    {
        "id": "Sled_Drag_-_Harness",
        "name": "Sled Drag - Harness",
        "met": 6
    },
    {
        "id": "Sled_Overhead_Backward_Walk",
        "name": "Sled Overhead Backward Walk",
        "met": 3.5
    },
    {
        "id": "Sled_Overhead_Triceps_Extension",
        "name": "Sled Overhead Triceps Extension",
        "met": 3
    },
    {
        "id": "Sled_Push",
        "name": "Sled Push",
        "met": 6
    },
    {
        "id": "Sled_Reverse_Flye",
        "name": "Sled Reverse Flye",
        "met": 3
    },
    {
        "id": "Sled_Row",
        "name": "Sled Row",
        "met": 3
    },
    {
        "id": "Sledgehammer_Swings",
        "name": "Sledgehammer Swings",
        "met": 8
    },
    {
        "id": "Smith_Incline_Shoulder_Raise",
        "name": "Smith Incline Shoulder Raise",
        "met": 3
    },
    {
        "id": "Smith_Machine_Behind_the_Back_Shrug",
        "name": "Smith Machine Behind the Back Shrug",
        "met": 3
    },
    {
        "id": "Smith_Machine_Bench_Press",
        "name": "Smith Machine Bench Press",
        "met": 3
    },
    {
        "id": "Smith_Machine_Bent_Over_Row",
        "name": "Smith Machine Bent Over Row",
        "met": 3
    },
    {
        "id": "Smith_Machine_Calf_Raise",
        "name": "Smith Machine Calf Raise",
        "met": 3
    },
    {
        "id": "Smith_Machine_Close-Grip_Bench_Press",
        "name": "Smith Machine Close-Grip Bench Press",
        "met": 3
    },
    {
        "id": "Smith_Machine_Decline_Press",
        "name": "Smith Machine Decline Press",
        "met": 3
    },
    {
        "id": "Smith_Machine_Hang_Power_Clean",
        "name": "Smith Machine Hang Power Clean",
        "met": 3
    },
    {
        "id": "Smith_Machine_Hip_Raise",
        "name": "Smith Machine Hip Raise",
        "met": 3
    },
    {
        "id": "Smith_Machine_Incline_Bench_Press",
        "name": "Smith Machine Incline Bench Press",
        "met": 3
    },
    {
        "id": "Smith_Machine_Leg_Press",
        "name": "Smith Machine Leg Press",
        "met": 3
    },
    {
        "id": "Smith_Machine_One-Arm_Upright_Row",
        "name": "Smith Machine One-Arm Upright Row",
        "met": 3
    },
    {
        "id": "Smith_Machine_Overhead_Shoulder_Press",
        "name": "Smith Machine Overhead Shoulder Press",
        "met": 3
    },
    {
        "id": "Smith_Machine_Pistol_Squat",
        "name": "Smith Machine Pistol Squat",
        "met": 3
    },
    {
        "id": "Smith_Machine_Reverse_Calf_Raises",
        "name": "Smith Machine Reverse Calf Raises",
        "met": 3
    },
    {
        "id": "Smith_Machine_Squat",
        "name": "Smith Machine Squat",
        "met": 3
    },
    {
        "id": "Smith_Machine_Stiff-Legged_Deadlift",
        "name": "Smith Machine Stiff-Legged Deadlift",
        "met": 3
    },
    {
        "id": "Smith_Machine_Upright_Row",
        "name": "Smith Machine Upright Row",
        "met": 3
    },
    {
        "id": "Smith_Single-Leg_Split_Squat",
        "name": "Smith Single-Leg Split Squat",
        "met": 3
    },
    {
        "id": "Snatch",
        "name": "Snatch",
        "met": 6
    },
    {
        "id": "Snatch_Balance",
        "name": "Snatch Balance",
        "met": 6
    },
    {
        "id": "Snatch_Deadlift",
        "name": "Snatch Deadlift",
        "met": 6
    },
    {
        "id": "Snatch_Pull",
        "name": "Snatch Pull",
        "met": 3
    },
    {
        "id": "Snatch_Shrug",
        "name": "Snatch Shrug",
        "met": 6
    },
    {
        "id": "Snatch_from_Blocks",
        "name": "Snatch from Blocks",
        "met": 6
    },
    {
        "id": "Speed_Band_Overhead_Triceps",
        "name": "Speed Band Overhead Triceps",
        "met": 3
    },
    {
        "id": "Speed_Box_Squat",
        "name": "Speed Box Squat",
        "met": 6
    },
    {
        "id": "Speed_Squats",
        "name": "Speed Squats",
        "met": 3
    },
    {
        "id": "Spell_Caster",
        "name": "Spell Caster",
        "met": 3
    },
    {
        "id": "Spider_Crawl",
        "name": "Spider Crawl",
        "met": 3
    },
    {
        "id": "Spider_Curl",
        "name": "Spider Curl",
        "met": 3
    },
    {
        "id": "Spinal_Stretch",
        "name": "Spinal Stretch",
        "met": 2
    },
    {
        "id": "Split_Clean",
        "name": "Split Clean",
        "met": 6
    },
    {
        "id": "Split_Jerk",
        "name": "Split Jerk",
        "met": 6
    },
    {
        "id": "Split_Jump",
        "name": "Split Jump",
        "met": 8
    },
    {
        "id": "Split_Snatch",
        "name": "Split Snatch",
        "met": 6
    },
    {
        "id": "Split_Squat_with_Dumbbells",
        "name": "Split Squat with Dumbbells",
        "met": 3
    },
    {
        "id": "Split_Squats",
        "name": "Split Squats",
        "met": 2
    },
    {
        "id": "Squat_Jerk",
        "name": "Squat Jerk",
        "met": 3
    },
    {
        "id": "Squat_with_Bands",
        "name": "Squat with Bands",
        "met": 6
    },
    {
        "id": "Squat_with_Chains",
        "name": "Squat with Chains",
        "met": 6
    },
    {
        "id": "Squat_with_Plate_Movers",
        "name": "Squat with Plate Movers",
        "met": 3
    },
    {
        "id": "Squats_-_With_Bands",
        "name": "Squats - With Bands",
        "met": 3
    },
    {
        "id": "Stairmaster",
        "name": "Stairmaster",
        "met": 8
    },
    {
        "id": "Standing_Alternating_Dumbbell_Press",
        "name": "Standing Alternating Dumbbell Press",
        "met": 3
    },
    {
        "id": "Standing_Barbell_Calf_Raise",
        "name": "Standing Barbell Calf Raise",
        "met": 3
    },
    {
        "id": "Standing_Barbell_Press_Behind_Neck",
        "name": "Standing Barbell Press Behind Neck",
        "met": 3
    },
    {
        "id": "Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension",
        "name": "Standing Bent-Over One-Arm Dumbbell Triceps Extension",
        "met": 3
    },
    {
        "id": "Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension",
        "name": "Standing Bent-Over Two-Arm Dumbbell Triceps Extension",
        "met": 3
    },
    {
        "id": "Standing_Biceps_Cable_Curl",
        "name": "Standing Biceps Cable Curl",
        "met": 3
    },
    {
        "id": "Standing_Biceps_Stretch",
        "name": "Standing Biceps Stretch",
        "met": 2
    },
    {
        "id": "Standing_Bradford_Press",
        "name": "Standing Bradford Press",
        "met": 3
    },
    {
        "id": "Standing_Cable_Chest_Press",
        "name": "Standing Cable Chest Press",
        "met": 3
    },
    {
        "id": "Standing_Cable_Lift",
        "name": "Standing Cable Lift",
        "met": 3
    },
    {
        "id": "Standing_Cable_Wood_Chop",
        "name": "Standing Cable Wood Chop",
        "met": 3
    },
    {
        "id": "Standing_Calf_Raises",
        "name": "Standing Calf Raises",
        "met": 3
    },
    {
        "id": "Standing_Concentration_Curl",
        "name": "Standing Concentration Curl",
        "met": 3
    },
    {
        "id": "Standing_Dumbbell_Calf_Raise",
        "name": "Standing Dumbbell Calf Raise",
        "met": 3
    },
    {
        "id": "Standing_Dumbbell_Press",
        "name": "Standing Dumbbell Press",
        "met": 3
    },
    {
        "id": "Standing_Dumbbell_Reverse_Curl",
        "name": "Standing Dumbbell Reverse Curl",
        "met": 3
    },
    {
        "id": "Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head",
        "name": "Standing Dumbbell Straight-Arm Front Delt Raise Above Head",
        "met": 3
    },
    {
        "id": "Standing_Dumbbell_Triceps_Extension",
        "name": "Standing Dumbbell Triceps Extension",
        "met": 3
    },
    {
        "id": "Standing_Dumbbell_Upright_Row",
        "name": "Standing Dumbbell Upright Row",
        "met": 3
    },
    {
        "id": "Standing_Elevated_Quad_Stretch",
        "name": "Standing Elevated Quad Stretch",
        "met": 2
    },
    {
        "id": "Standing_Front_Barbell_Raise_Over_Head",
        "name": "Standing Front Barbell Raise Over Head",
        "met": 3
    },
    {
        "id": "Standing_Gastrocnemius_Calf_Stretch",
        "name": "Standing Gastrocnemius Calf Stretch",
        "met": 2
    },
    {
        "id": "Standing_Hamstring_and_Calf_Stretch",
        "name": "Standing Hamstring and Calf Stretch",
        "met": 2
    },
    {
        "id": "Standing_Hip_Circles",
        "name": "Standing Hip Circles",
        "met": 2
    },
    {
        "id": "Standing_Hip_Flexors",
        "name": "Standing Hip Flexors",
        "met": 2
    },
    {
        "id": "Standing_Inner-Biceps_Curl",
        "name": "Standing Inner-Biceps Curl",
        "met": 3
    },
    {
        "id": "Standing_Lateral_Stretch",
        "name": "Standing Lateral Stretch",
        "met": 2
    },
    {
        "id": "Standing_Leg_Curl",
        "name": "Standing Leg Curl",
        "met": 3
    },
    {
        "id": "Standing_Long_Jump",
        "name": "Standing Long Jump",
        "met": 8
    },
    {
        "id": "Standing_Low-Pulley_Deltoid_Raise",
        "name": "Standing Low-Pulley Deltoid Raise",
        "met": 3
    },
    {
        "id": "Standing_Low-Pulley_One-Arm_Triceps_Extension",
        "name": "Standing Low-Pulley One-Arm Triceps Extension",
        "met": 3
    },
    {
        "id": "Standing_Military_Press",
        "name": "Standing Military Press",
        "met": 3
    },
    {
        "id": "Standing_Olympic_Plate_Hand_Squeeze",
        "name": "Standing Olympic Plate Hand Squeeze",
        "met": 3
    },
    {
        "id": "Standing_One-Arm_Cable_Curl",
        "name": "Standing One-Arm Cable Curl",
        "met": 3
    },
    {
        "id": "Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench",
        "name": "Standing One-Arm Dumbbell Curl Over Incline Bench",
        "met": 3
    },
    {
        "id": "Standing_One-Arm_Dumbbell_Triceps_Extension",
        "name": "Standing One-Arm Dumbbell Triceps Extension",
        "met": 3
    },
    {
        "id": "Standing_Overhead_Barbell_Triceps_Extension",
        "name": "Standing Overhead Barbell Triceps Extension",
        "met": 3
    },
    {
        "id": "Standing_Palm-In_One-Arm_Dumbbell_Press",
        "name": "Standing Palm-In One-Arm Dumbbell Press",
        "met": 3
    },
    {
        "id": "Standing_Palms-In_Dumbbell_Press",
        "name": "Standing Palms-In Dumbbell Press",
        "met": 3
    },
    {
        "id": "Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl",
        "name": "Standing Palms-Up Barbell Behind The Back Wrist Curl",
        "met": 3
    },
    {
        "id": "Standing_Pelvic_Tilt",
        "name": "Standing Pelvic Tilt",
        "met": 2
    },
    {
        "id": "Standing_Rope_Crunch",
        "name": "Standing Rope Crunch",
        "met": 8
    },
    {
        "id": "Standing_Soleus_And_Achilles_Stretch",
        "name": "Standing Soleus And Achilles Stretch",
        "met": 2
    },
    {
        "id": "Standing_Toe_Touches",
        "name": "Standing Toe Touches",
        "met": 2
    },
    {
        "id": "Standing_Towel_Triceps_Extension",
        "name": "Standing Towel Triceps Extension",
        "met": 3
    },
    {
        "id": "Standing_Two-Arm_Overhead_Throw",
        "name": "Standing Two-Arm Overhead Throw",
        "met": 8
    },
    {
        "id": "Star_Jump",
        "name": "Star Jump",
        "met": 8
    },
    {
        "id": "Step-up_with_Knee_Raise",
        "name": "Step-up with Knee Raise",
        "met": 3
    },
    {
        "id": "Step_Mill",
        "name": "Step Mill",
        "met": 8
    },
    {
        "id": "Stiff-Legged_Barbell_Deadlift",
        "name": "Stiff-Legged Barbell Deadlift",
        "met": 3
    },
    {
        "id": "Stiff-Legged_Dumbbell_Deadlift",
        "name": "Stiff-Legged Dumbbell Deadlift",
        "met": 3
    },
    {
        "id": "Stiff_Leg_Barbell_Good_Morning",
        "name": "Stiff Leg Barbell Good Morning",
        "met": 3
    },
    {
        "id": "Stomach_Vacuum",
        "name": "Stomach Vacuum",
        "met": 2
    },
    {
        "id": "Straight-Arm_Dumbbell_Pullover",
        "name": "Straight-Arm Dumbbell Pullover",
        "met": 3
    },
    {
        "id": "Straight-Arm_Pulldown",
        "name": "Straight-Arm Pulldown",
        "met": 3
    },
    {
        "id": "Straight_Bar_Bench_Mid_Rows",
        "name": "Straight Bar Bench Mid Rows",
        "met": 3
    },
    {
        "id": "Straight_Raises_on_Incline_Bench",
        "name": "Straight Raises on Incline Bench",
        "met": 3
    },
    {
        "id": "Stride_Jump_Crossover",
        "name": "Stride Jump Crossover",
        "met": 8
    },
    {
        "id": "Sumo_Deadlift",
        "name": "Sumo Deadlift",
        "met": 6
    },
    {
        "id": "Sumo_Deadlift_with_Bands",
        "name": "Sumo Deadlift with Bands",
        "met": 6
    },
    {
        "id": "Sumo_Deadlift_with_Chains",
        "name": "Sumo Deadlift with Chains",
        "met": 6
    },
    {
        "id": "Superman",
        "name": "Superman",
        "met": 2
    },
    {
        "id": "Supine_Chest_Throw",
        "name": "Supine Chest Throw",
        "met": 8
    },
    {
        "id": "Supine_One-Arm_Overhead_Throw",
        "name": "Supine One-Arm Overhead Throw",
        "met": 8
    },
    {
        "id": "Supine_Two-Arm_Overhead_Throw",
        "name": "Supine Two-Arm Overhead Throw",
        "met": 8
    },
    {
        "id": "Suspended_Fallout",
        "name": "Suspended Fallout",
        "met": 3
    },
    {
        "id": "Suspended_Push-Up",
        "name": "Suspended Push-Up",
        "met": 3
    },
    {
        "id": "Suspended_Reverse_Crunch",
        "name": "Suspended Reverse Crunch",
        "met": 8
    },
    {
        "id": "Suspended_Row",
        "name": "Suspended Row",
        "met": 3
    },
    {
        "id": "Suspended_Split_Squat",
        "name": "Suspended Split Squat",
        "met": 3
    },
    {
        "id": "Svend_Press",
        "name": "Svend Press",
        "met": 3
    },
    {
        "id": "T-Bar_Row_with_Handle",
        "name": "T-Bar Row with Handle",
        "met": 3
    },
    {
        "id": "Tate_Press",
        "name": "Tate Press",
        "met": 3
    },
    {
        "id": "The_Straddle",
        "name": "The Straddle",
        "met": 2
    },
    {
        "id": "Thigh_Abductor",
        "name": "Thigh Abductor",
        "met": 3
    },
    {
        "id": "Thigh_Adductor",
        "name": "Thigh Adductor",
        "met": 3
    },
    {
        "id": "Tire_Flip",
        "name": "Tire Flip",
        "met": 6
    },
    {
        "id": "Toe_Touchers",
        "name": "Toe Touchers",
        "met": 2
    },
    {
        "id": "Torso_Rotation",
        "name": "Torso Rotation",
        "met": 2
    },
    {
        "id": "Trail_Running_Walking",
        "name": "Trail Running/Walking",
        "met": 8
    },
    {
        "id": "Trap_Bar_Deadlift",
        "name": "Trap Bar Deadlift",
        "met": 3
    },
    {
        "id": "Tricep_Dumbbell_Kickback",
        "name": "Tricep Dumbbell Kickback",
        "met": 3
    },
    {
        "id": "Tricep_Side_Stretch",
        "name": "Tricep Side Stretch",
        "met": 2
    },
    {
        "id": "Triceps_Overhead_Extension_with_Rope",
        "name": "Triceps Overhead Extension with Rope",
        "met": 3
    },
    {
        "id": "Triceps_Pushdown",
        "name": "Triceps Pushdown",
        "met": 3
    },
    {
        "id": "Triceps_Pushdown_-_Rope_Attachment",
        "name": "Triceps Pushdown - Rope Attachment",
        "met": 3
    },
    {
        "id": "Triceps_Pushdown_-_V-Bar_Attachment",
        "name": "Triceps Pushdown - V-Bar Attachment",
        "met": 3
    },
    {
        "id": "Triceps_Stretch",
        "name": "Triceps Stretch",
        "met": 2
    },
    {
        "id": "Tuck_Crunch",
        "name": "Tuck Crunch",
        "met": 8
    },
    {
        "id": "Two-Arm_Dumbbell_Preacher_Curl",
        "name": "Two-Arm Dumbbell Preacher Curl",
        "met": 3
    },
    {
        "id": "Two-Arm_Kettlebell_Clean",
        "name": "Two-Arm Kettlebell Clean",
        "met": 3
    },
    {
        "id": "Two-Arm_Kettlebell_Jerk",
        "name": "Two-Arm Kettlebell Jerk",
        "met": 3
    },
    {
        "id": "Two-Arm_Kettlebell_Military_Press",
        "name": "Two-Arm Kettlebell Military Press",
        "met": 3
    },
    {
        "id": "Two-Arm_Kettlebell_Row",
        "name": "Two-Arm Kettlebell Row",
        "met": 3
    },
    {
        "id": "Underhand_Cable_Pulldowns",
        "name": "Underhand Cable Pulldowns",
        "met": 3
    },
    {
        "id": "Upper_Back-Leg_Grab",
        "name": "Upper Back-Leg Grab",
        "met": 2
    },
    {
        "id": "Upper_Back_Stretch",
        "name": "Upper Back Stretch",
        "met": 2
    },
    {
        "id": "Upright_Barbell_Row",
        "name": "Upright Barbell Row",
        "met": 3
    },
    {
        "id": "Upright_Cable_Row",
        "name": "Upright Cable Row",
        "met": 3
    },
    {
        "id": "Upright_Row_-_With_Bands",
        "name": "Upright Row - With Bands",
        "met": 3
    },
    {
        "id": "Upward_Stretch",
        "name": "Upward Stretch",
        "met": 2
    },
    {
        "id": "V-Bar_Pulldown",
        "name": "V-Bar Pulldown",
        "met": 3
    },
    {
        "id": "V-Bar_Pullup",
        "name": "V-Bar Pullup",
        "met": 3
    },
    {
        "id": "Vertical_Swing",
        "name": "Vertical Swing",
        "met": 8
    },
    {
        "id": "Walking_Treadmill",
        "name": "Walking, Treadmill",
        "met": 8
    },
    {
        "id": "Weighted_Ball_Hyperextension",
        "name": "Weighted Ball Hyperextension",
        "met": 3
    },
    {
        "id": "Weighted_Ball_Side_Bend",
        "name": "Weighted Ball Side Bend",
        "met": 3
    },
    {
        "id": "Weighted_Bench_Dip",
        "name": "Weighted Bench Dip",
        "met": 3
    },
    {
        "id": "Weighted_Crunches",
        "name": "Weighted Crunches",
        "met": 8
    },
    {
        "id": "Weighted_Jump_Squat",
        "name": "Weighted Jump Squat",
        "met": 3
    },
    {
        "id": "Weighted_Pull_Ups",
        "name": "Weighted Pull Ups",
        "met": 3
    },
    {
        "id": "Weighted_Sissy_Squat",
        "name": "Weighted Sissy Squat",
        "met": 3
    },
    {
        "id": "Weighted_Sit-Ups_-_With_Bands",
        "name": "Weighted Sit-Ups - With Bands",
        "met": 3
    },
    {
        "id": "Weighted_Squat",
        "name": "Weighted Squat",
        "met": 3
    },
    {
        "id": "Wide-Grip_Barbell_Bench_Press",
        "name": "Wide-Grip Barbell Bench Press",
        "met": 3
    },
    {
        "id": "Wide-Grip_Decline_Barbell_Bench_Press",
        "name": "Wide-Grip Decline Barbell Bench Press",
        "met": 3
    },
    {
        "id": "Wide-Grip_Decline_Barbell_Pullover",
        "name": "Wide-Grip Decline Barbell Pullover",
        "met": 3
    },
    {
        "id": "Wide-Grip_Lat_Pulldown",
        "name": "Wide-Grip Lat Pulldown",
        "met": 3
    },
    {
        "id": "Wide-Grip_Pulldown_Behind_The_Neck",
        "name": "Wide-Grip Pulldown Behind The Neck",
        "met": 3
    },
    {
        "id": "Wide-Grip_Rear_Pull-Up",
        "name": "Wide-Grip Rear Pull-Up",
        "met": 3
    },
    {
        "id": "Wide-Grip_Standing_Barbell_Curl",
        "name": "Wide-Grip Standing Barbell Curl",
        "met": 3
    },
    {
        "id": "Wide_Stance_Barbell_Squat",
        "name": "Wide Stance Barbell Squat",
        "met": 3
    },
    {
        "id": "Wide_Stance_Stiff_Legs",
        "name": "Wide Stance Stiff Legs",
        "met": 6
    },
    {
        "id": "Wind_Sprints",
        "name": "Wind Sprints",
        "met": 3
    },
    {
        "id": "Windmills",
        "name": "Windmills",
        "met": 2
    },
    {
        "id": "Worlds_Greatest_Stretch",
        "name": "World's Greatest Stretch",
        "met": 2
    },
    {
        "id": "Wrist_Circles",
        "name": "Wrist Circles",
        "met": 2
    },
    {
        "id": "Wrist_Roller",
        "name": "Wrist Roller",
        "met": 3
    },
    {
        "id": "Wrist_Rotations_with_Straight_Bar",
        "name": "Wrist Rotations with Straight Bar",
        "met": 3
    },
    {
        "id": "Yoke_Walk",
        "name": "Yoke Walk",
        "met": 3.5
    },
    {
        "id": "Zercher_Squats",
        "name": "Zercher Squats",
        "met": 3
    },
    {
        "id": "Zottman_Curl",
        "name": "Zottman Curl",
        "met": 3
    },
    {
        "id": "Zottman_Preacher_Curl",
        "name": "Zottman Preacher Curl",
        "met": 3
    }
];
